package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblCompanyMaster generated by hbm2java
 */
public class TblCompanyMaster  implements java.io.Serializable {


     private Integer compId;
     private TblEmpMaster tblEmpMaster;
     private String compCode;
     private String compName;
     private int compStatus;
     private Date compLmd;
     private Set tblMapCompanyLocations = new HashSet(0);
     private Set tblMapCompanyDepartments = new HashSet(0);
     private Set tblEmpMasters = new HashSet(0);

    public TblCompanyMaster() {
    }

	
    public TblCompanyMaster(String compCode, String compName, int compStatus, Date compLmd) {
        this.compCode = compCode;
        this.compName = compName;
        this.compStatus = compStatus;
        this.compLmd = compLmd;
    }
    public TblCompanyMaster(TblEmpMaster tblEmpMaster, String compCode, String compName, int compStatus, Date compLmd, Set tblMapCompanyLocations, Set tblMapCompanyDepartments, Set tblEmpMasters) {
       this.tblEmpMaster = tblEmpMaster;
       this.compCode = compCode;
       this.compName = compName;
       this.compStatus = compStatus;
       this.compLmd = compLmd;
       this.tblMapCompanyLocations = tblMapCompanyLocations;
       this.tblMapCompanyDepartments = tblMapCompanyDepartments;
       this.tblEmpMasters = tblEmpMasters;
    }
   
    public Integer getCompId() {
        return this.compId;
    }
    
    public void setCompId(Integer compId) {
        this.compId = compId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getCompCode() {
        return this.compCode;
    }
    
    public void setCompCode(String compCode) {
        this.compCode = compCode;
    }
    public String getCompName() {
        return this.compName;
    }
    
    public void setCompName(String compName) {
        this.compName = compName;
    }
    public int getCompStatus() {
        return this.compStatus;
    }
    
    public void setCompStatus(int compStatus) {
        this.compStatus = compStatus;
    }
    public Date getCompLmd() {
        return this.compLmd;
    }
    
    public void setCompLmd(Date compLmd) {
        this.compLmd = compLmd;
    }
    public Set getTblMapCompanyLocations() {
        return this.tblMapCompanyLocations;
    }
    
    public void setTblMapCompanyLocations(Set tblMapCompanyLocations) {
        this.tblMapCompanyLocations = tblMapCompanyLocations;
    }
    public Set getTblMapCompanyDepartments() {
        return this.tblMapCompanyDepartments;
    }
    
    public void setTblMapCompanyDepartments(Set tblMapCompanyDepartments) {
        this.tblMapCompanyDepartments = tblMapCompanyDepartments;
    }
    public Set getTblEmpMasters() {
        return this.tblEmpMasters;
    }
    
    public void setTblEmpMasters(Set tblEmpMasters) {
        this.tblEmpMasters = tblEmpMasters;
    }




}


