package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblDepartmentMaster generated by hbm2java
 */
public class TblDepartmentMaster  implements java.io.Serializable {


     private Integer deptId;
     private TblEmpMaster tblEmpMaster;
     private String deptCode;
     private String deptName;
     private int deptStatus;
     private Date deptLmd;
     private Set tblMapCompanyDepartments = new HashSet(0);
     private Set tblIndentMasters = new HashSet(0);
     private Set tblEmpMasters = new HashSet(0);

    public TblDepartmentMaster() {
    }

	
    public TblDepartmentMaster(TblEmpMaster tblEmpMaster, String deptName, int deptStatus, Date deptLmd) {
        this.tblEmpMaster = tblEmpMaster;
        this.deptName = deptName;
        this.deptStatus = deptStatus;
        this.deptLmd = deptLmd;
    }
    public TblDepartmentMaster(TblEmpMaster tblEmpMaster, String deptCode, String deptName, int deptStatus, Date deptLmd, Set tblMapCompanyDepartments, Set tblIndentMasters, Set tblEmpMasters) {
       this.tblEmpMaster = tblEmpMaster;
       this.deptCode = deptCode;
       this.deptName = deptName;
       this.deptStatus = deptStatus;
       this.deptLmd = deptLmd;
       this.tblMapCompanyDepartments = tblMapCompanyDepartments;
       this.tblIndentMasters = tblIndentMasters;
       this.tblEmpMasters = tblEmpMasters;
    }
   
    public Integer getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getDeptCode() {
        return this.deptCode;
    }
    
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
    public int getDeptStatus() {
        return this.deptStatus;
    }
    
    public void setDeptStatus(int deptStatus) {
        this.deptStatus = deptStatus;
    }
    public Date getDeptLmd() {
        return this.deptLmd;
    }
    
    public void setDeptLmd(Date deptLmd) {
        this.deptLmd = deptLmd;
    }
    public Set getTblMapCompanyDepartments() {
        return this.tblMapCompanyDepartments;
    }
    
    public void setTblMapCompanyDepartments(Set tblMapCompanyDepartments) {
        this.tblMapCompanyDepartments = tblMapCompanyDepartments;
    }
    public Set getTblIndentMasters() {
        return this.tblIndentMasters;
    }
    
    public void setTblIndentMasters(Set tblIndentMasters) {
        this.tblIndentMasters = tblIndentMasters;
    }
    public Set getTblEmpMasters() {
        return this.tblEmpMasters;
    }
    
    public void setTblEmpMasters(Set tblEmpMasters) {
        this.tblEmpMasters = tblEmpMasters;
    }




}


