package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblEmpMaster generated by hbm2java
 */
public class TblEmpMaster  implements java.io.Serializable {


     private Integer empNumber;
     private TblDepartmentMaster tblDepartmentMaster;
     private TblLocationMaster tblLocationMaster;
     private String empId;
     private String empName;
     private String empEmail;
     private String empPassword;
     private Date empJoinDate;
     private String empDesignation;
     private String empCostCenter;
     private String empPath;
     private int empStatus;
     private Date empLmd;
     private Set tblRolesMasters = new HashSet(0);
     private Set tblMapEmpRolesesForEmpNumber = new HashSet(0);
     private Set tblDepartmentMasters = new HashSet(0);
     private Set tblMapEmpRolesesForEmpRolesLmu = new HashSet(0);
     private Set tblMapCompanyDepartments = new HashSet(0);
     private Set tblIndentMastersForIndentEmp = new HashSet(0);
     private Set tblIndentStatuses = new HashSet(0);
     private Set tblIndentMastersForIndentLmu = new HashSet(0);
     private Set tblIndentMastersForIndentFinalApprovedby = new HashSet(0);
     private Set tblIndentMastersForIndentCreatedby = new HashSet(0);
     private Set tblMapCompanyLocations = new HashSet(0);
     private Set tblIndentMastersForIndentApprovedby = new HashSet(0);
     private Set tblCompanyMasters = new HashSet(0);
     private Set tblSectionMasters = new HashSet(0);
     private Set tblMapEmpReportingsForReportLmu = new HashSet(0);
     private Set tblUserMastersForEmpNumber = new HashSet(0);
     private Set tblLocationMasters = new HashSet(0);
     private Set tblUserMastersForUserLmu = new HashSet(0);
     private Set tblMapEmpReportingsForReportSub = new HashSet(0);
     private Set tblMapEmpReportingsForReportSup = new HashSet(0);
     
     private String empPlant;

    public TblEmpMaster() {
    }

    public TblEmpMaster(Integer empNumber, TblDepartmentMaster tblDepartmentMaster, TblLocationMaster tblLocationMaster, String empId, String empName, String empEmail, String empPassword, Date empJoinDate, String empDesignation, String empCostCenter, String empPath, int empStatus, Date empLmd, String empPlant) {
        this.empNumber = empNumber;
        this.tblDepartmentMaster = tblDepartmentMaster;
        this.tblLocationMaster = tblLocationMaster;
        this.empId = empId;
        this.empName = empName;
        this.empEmail = empEmail;
        this.empPassword = empPassword;
        this.empJoinDate = empJoinDate;
        this.empDesignation = empDesignation;
        this.empCostCenter = empCostCenter;
        this.empPath = empPath;
        this.empStatus = empStatus;
        this.empLmd = empLmd;
        this.empPlant = empPlant;
    }

    public TblEmpMaster(TblDepartmentMaster tblDepartmentMaster, TblLocationMaster tblLocationMaster, String empId, String empName, String empEmail, String empPassword, Date empJoinDate, String empDesignation, String empCostCenter, String empPath, int empStatus, Date empLmd, String empPlant) {
        this.tblDepartmentMaster = tblDepartmentMaster;
        this.tblLocationMaster = tblLocationMaster;
        this.empId = empId;
        this.empName = empName;
        this.empEmail = empEmail;
        this.empPassword = empPassword;
        this.empJoinDate = empJoinDate;
        this.empDesignation = empDesignation;
        this.empCostCenter = empCostCenter;
        this.empPath = empPath;
        this.empStatus = empStatus;
        this.empLmd = empLmd;
        this.empPlant = empPlant;
    }

    public Integer getEmpNumber() {
        return empNumber;
    }

    public void setEmpNumber(Integer empNumber) {
        this.empNumber = empNumber;
    }

    public TblDepartmentMaster getTblDepartmentMaster() {
        return tblDepartmentMaster;
    }

    public void setTblDepartmentMaster(TblDepartmentMaster tblDepartmentMaster) {
        this.tblDepartmentMaster = tblDepartmentMaster;
    }

    public TblLocationMaster getTblLocationMaster() {
        return tblLocationMaster;
    }

    public void setTblLocationMaster(TblLocationMaster tblLocationMaster) {
        this.tblLocationMaster = tblLocationMaster;
    }

    public String getEmpId() {
        return empId;
    }

    public void setEmpId(String empId) {
        this.empId = empId;
    }

    public String getEmpName() {
        return empName;
    }

    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public String getEmpEmail() {
        return empEmail;
    }

    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail;
    }

    public String getEmpPassword() {
        return empPassword;
    }

    public void setEmpPassword(String empPassword) {
        this.empPassword = empPassword;
    }

    public Date getEmpJoinDate() {
        return empJoinDate;
    }

    public void setEmpJoinDate(Date empJoinDate) {
        this.empJoinDate = empJoinDate;
    }

    public String getEmpDesignation() {
        return empDesignation;
    }

    public void setEmpDesignation(String empDesignation) {
        this.empDesignation = empDesignation;
    }

    public String getEmpCostCenter() {
        return empCostCenter;
    }

    public void setEmpCostCenter(String empCostCenter) {
        this.empCostCenter = empCostCenter;
    }

    public String getEmpPath() {
        return empPath;
    }

    public void setEmpPath(String empPath) {
        this.empPath = empPath;
    }

    public int getEmpStatus() {
        return empStatus;
    }

    public void setEmpStatus(int empStatus) {
        this.empStatus = empStatus;
    }

    public Date getEmpLmd() {
        return empLmd;
    }

    public void setEmpLmd(Date empLmd) {
        this.empLmd = empLmd;
    }

    public Set getTblRolesMasters() {
        return tblRolesMasters;
    }

    public void setTblRolesMasters(Set tblRolesMasters) {
        this.tblRolesMasters = tblRolesMasters;
    }

    public Set getTblMapEmpRolesesForEmpNumber() {
        return tblMapEmpRolesesForEmpNumber;
    }

    public void setTblMapEmpRolesesForEmpNumber(Set tblMapEmpRolesesForEmpNumber) {
        this.tblMapEmpRolesesForEmpNumber = tblMapEmpRolesesForEmpNumber;
    }

    public Set getTblDepartmentMasters() {
        return tblDepartmentMasters;
    }

    public void setTblDepartmentMasters(Set tblDepartmentMasters) {
        this.tblDepartmentMasters = tblDepartmentMasters;
    }

    public Set getTblMapEmpRolesesForEmpRolesLmu() {
        return tblMapEmpRolesesForEmpRolesLmu;
    }

    public void setTblMapEmpRolesesForEmpRolesLmu(Set tblMapEmpRolesesForEmpRolesLmu) {
        this.tblMapEmpRolesesForEmpRolesLmu = tblMapEmpRolesesForEmpRolesLmu;
    }

    public Set getTblMapCompanyDepartments() {
        return tblMapCompanyDepartments;
    }

    public void setTblMapCompanyDepartments(Set tblMapCompanyDepartments) {
        this.tblMapCompanyDepartments = tblMapCompanyDepartments;
    }

    public Set getTblIndentMastersForIndentEmp() {
        return tblIndentMastersForIndentEmp;
    }

    public void setTblIndentMastersForIndentEmp(Set tblIndentMastersForIndentEmp) {
        this.tblIndentMastersForIndentEmp = tblIndentMastersForIndentEmp;
    }

    public Set getTblIndentStatuses() {
        return tblIndentStatuses;
    }

    public void setTblIndentStatuses(Set tblIndentStatuses) {
        this.tblIndentStatuses = tblIndentStatuses;
    }

    public Set getTblIndentMastersForIndentLmu() {
        return tblIndentMastersForIndentLmu;
    }

    public void setTblIndentMastersForIndentLmu(Set tblIndentMastersForIndentLmu) {
        this.tblIndentMastersForIndentLmu = tblIndentMastersForIndentLmu;
    }

    public Set getTblIndentMastersForIndentFinalApprovedby() {
        return tblIndentMastersForIndentFinalApprovedby;
    }

    public void setTblIndentMastersForIndentFinalApprovedby(Set tblIndentMastersForIndentFinalApprovedby) {
        this.tblIndentMastersForIndentFinalApprovedby = tblIndentMastersForIndentFinalApprovedby;
    }

    public Set getTblIndentMastersForIndentCreatedby() {
        return tblIndentMastersForIndentCreatedby;
    }

    public void setTblIndentMastersForIndentCreatedby(Set tblIndentMastersForIndentCreatedby) {
        this.tblIndentMastersForIndentCreatedby = tblIndentMastersForIndentCreatedby;
    }

    public Set getTblMapCompanyLocations() {
        return tblMapCompanyLocations;
    }

    public void setTblMapCompanyLocations(Set tblMapCompanyLocations) {
        this.tblMapCompanyLocations = tblMapCompanyLocations;
    }

    public Set getTblIndentMastersForIndentApprovedby() {
        return tblIndentMastersForIndentApprovedby;
    }

    public void setTblIndentMastersForIndentApprovedby(Set tblIndentMastersForIndentApprovedby) {
        this.tblIndentMastersForIndentApprovedby = tblIndentMastersForIndentApprovedby;
    }

    public Set getTblCompanyMasters() {
        return tblCompanyMasters;
    }

    public void setTblCompanyMasters(Set tblCompanyMasters) {
        this.tblCompanyMasters = tblCompanyMasters;
    }

    public Set getTblSectionMasters() {
        return tblSectionMasters;
    }

    public void setTblSectionMasters(Set tblSectionMasters) {
        this.tblSectionMasters = tblSectionMasters;
    }

    public Set getTblMapEmpReportingsForReportLmu() {
        return tblMapEmpReportingsForReportLmu;
    }

    public void setTblMapEmpReportingsForReportLmu(Set tblMapEmpReportingsForReportLmu) {
        this.tblMapEmpReportingsForReportLmu = tblMapEmpReportingsForReportLmu;
    }

    public Set getTblUserMastersForEmpNumber() {
        return tblUserMastersForEmpNumber;
    }

    public void setTblUserMastersForEmpNumber(Set tblUserMastersForEmpNumber) {
        this.tblUserMastersForEmpNumber = tblUserMastersForEmpNumber;
    }

    public Set getTblLocationMasters() {
        return tblLocationMasters;
    }

    public void setTblLocationMasters(Set tblLocationMasters) {
        this.tblLocationMasters = tblLocationMasters;
    }

    public Set getTblUserMastersForUserLmu() {
        return tblUserMastersForUserLmu;
    }

    public void setTblUserMastersForUserLmu(Set tblUserMastersForUserLmu) {
        this.tblUserMastersForUserLmu = tblUserMastersForUserLmu;
    }

    public Set getTblMapEmpReportingsForReportSub() {
        return tblMapEmpReportingsForReportSub;
    }

    public void setTblMapEmpReportingsForReportSub(Set tblMapEmpReportingsForReportSub) {
        this.tblMapEmpReportingsForReportSub = tblMapEmpReportingsForReportSub;
    }

    public Set getTblMapEmpReportingsForReportSup() {
        return tblMapEmpReportingsForReportSup;
    }

    public void setTblMapEmpReportingsForReportSup(Set tblMapEmpReportingsForReportSup) {
        this.tblMapEmpReportingsForReportSup = tblMapEmpReportingsForReportSup;
    }

    public String getEmpPlant() {
        return empPlant;
    }

    public void setEmpPlant(String empPlant) {
        this.empPlant = empPlant;
    }

	
    




}


