package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TblGoodsReceipt generated by hbm2java
 */
public class TblGoodsReceipt  implements java.io.Serializable {


     private Integer goodsReceiptId;
     private TblEmpMaster tblEmpMasterByGoodsReceiptLmu;
     private TblEmpMaster tblEmpMasterByGoodsReceiptCreatedby;
     private TblEmpMaster tblEmpMasterByGoodsReceiptApprovedby;
     private TblEmpMaster tblEmpMasterByGoodsReceiptFinalApprovedby;
     private TblEmpMaster tblEmpMasterByGoodsReceiptStoresby;
     private TblIndentDetails tblIndentDetails;
     private TblIndentMaster tblIndentMaster;
     private TblIndentStatus tblIndentStatusByGoodsReceiptFinalStatus;
     private TblIndentStatus tblIndentStatusByGoodsReceiptStoresbyStatus;
     private TblIndentStatus tblIndentStatusByGoodsReceiptApprovedStatus;
     private BigDecimal goodsReceiptQuantity;
     private BigDecimal goodsReceiptIssuedQuantity;
     private BigDecimal goodsReceiptBalanceInventory;
     private BigDecimal goodsReceiptOpeningQuantity;
     private String goodsReceiptCreatedDate;
     private String goodsReceiptCreatedRemarks;
     private String goodsReceiptApprovedbyDate;
     private String goodsReceiptApprovedbyRemarks;
     private String goodsReceiptFinalApprovedbyDate;
     private String goodsReceiptFinalApprovedbyRemarks;
     private BigDecimal goodsReceiptRequestedQuantity;
     private BigDecimal goodsReceiptBalanceQuantityStores;
     private String goodsReceiptStoresbyDate;
     private String goodsReceiptStoresbyRemarks;
     private int goodsReceiptStatus;
     private String goodsReceiptLmd;

    public TblGoodsReceipt() {
    }

	
    public TblGoodsReceipt(TblEmpMaster tblEmpMasterByGoodsReceiptLmu, TblIndentDetails tblIndentDetails, TblIndentMaster tblIndentMaster, int goodsReceiptStatus, String goodsReceiptLmd) {
        this.tblEmpMasterByGoodsReceiptLmu = tblEmpMasterByGoodsReceiptLmu;
        this.tblIndentDetails = tblIndentDetails;
        this.tblIndentMaster = tblIndentMaster;
        this.goodsReceiptStatus = goodsReceiptStatus;
        this.goodsReceiptLmd = goodsReceiptLmd;
    }
    public TblGoodsReceipt(TblEmpMaster tblEmpMasterByGoodsReceiptLmu, TblEmpMaster tblEmpMasterByGoodsReceiptCreatedby, TblEmpMaster tblEmpMasterByGoodsReceiptApprovedby, TblEmpMaster tblEmpMasterByGoodsReceiptFinalApprovedby, TblEmpMaster tblEmpMasterByGoodsReceiptStoresby, TblIndentDetails tblIndentDetails, TblIndentMaster tblIndentMaster, TblIndentStatus tblIndentStatusByGoodsReceiptFinalStatus, TblIndentStatus tblIndentStatusByGoodsReceiptStoresbyStatus, TblIndentStatus tblIndentStatusByGoodsReceiptApprovedStatus, BigDecimal goodsReceiptQuantity, BigDecimal goodsReceiptIssuedQuantity, BigDecimal goodsReceiptBalanceInventory, BigDecimal goodsReceiptOpeningQuantity, String goodsReceiptCreatedDate, String goodsReceiptCreatedRemarks, String goodsReceiptApprovedbyDate, String goodsReceiptApprovedbyRemarks, String goodsReceiptFinalApprovedbyDate, String goodsReceiptFinalApprovedbyRemarks, BigDecimal goodsReceiptRequestedQuantity, BigDecimal goodsReceiptBalanceQuantityStores, String goodsReceiptStoresbyDate, String goodsReceiptStoresbyRemarks, int goodsReceiptStatus, String goodsReceiptLmd) {
       this.tblEmpMasterByGoodsReceiptLmu = tblEmpMasterByGoodsReceiptLmu;
       this.tblEmpMasterByGoodsReceiptCreatedby = tblEmpMasterByGoodsReceiptCreatedby;
       this.tblEmpMasterByGoodsReceiptApprovedby = tblEmpMasterByGoodsReceiptApprovedby;
       this.tblEmpMasterByGoodsReceiptFinalApprovedby = tblEmpMasterByGoodsReceiptFinalApprovedby;
       this.tblEmpMasterByGoodsReceiptStoresby = tblEmpMasterByGoodsReceiptStoresby;
       this.tblIndentDetails = tblIndentDetails;
       this.tblIndentMaster = tblIndentMaster;
       this.tblIndentStatusByGoodsReceiptFinalStatus = tblIndentStatusByGoodsReceiptFinalStatus;
       this.tblIndentStatusByGoodsReceiptStoresbyStatus = tblIndentStatusByGoodsReceiptStoresbyStatus;
       this.tblIndentStatusByGoodsReceiptApprovedStatus = tblIndentStatusByGoodsReceiptApprovedStatus;
       this.goodsReceiptQuantity = goodsReceiptQuantity;
       this.goodsReceiptIssuedQuantity = goodsReceiptIssuedQuantity;
       this.goodsReceiptBalanceInventory = goodsReceiptBalanceInventory;
       this.goodsReceiptOpeningQuantity = goodsReceiptOpeningQuantity;
       this.goodsReceiptCreatedDate = goodsReceiptCreatedDate;
       this.goodsReceiptCreatedRemarks = goodsReceiptCreatedRemarks;
       this.goodsReceiptApprovedbyDate = goodsReceiptApprovedbyDate;
       this.goodsReceiptApprovedbyRemarks = goodsReceiptApprovedbyRemarks;
       this.goodsReceiptFinalApprovedbyDate = goodsReceiptFinalApprovedbyDate;
       this.goodsReceiptFinalApprovedbyRemarks = goodsReceiptFinalApprovedbyRemarks;
       this.goodsReceiptRequestedQuantity = goodsReceiptRequestedQuantity;
       this.goodsReceiptBalanceQuantityStores = goodsReceiptBalanceQuantityStores;
       this.goodsReceiptStoresbyDate = goodsReceiptStoresbyDate;
       this.goodsReceiptStoresbyRemarks = goodsReceiptStoresbyRemarks;
       this.goodsReceiptStatus = goodsReceiptStatus;
       this.goodsReceiptLmd = goodsReceiptLmd;
    }
   
    public Integer getGoodsReceiptId() {
        return this.goodsReceiptId;
    }
    
    public void setGoodsReceiptId(Integer goodsReceiptId) {
        this.goodsReceiptId = goodsReceiptId;
    }
    public TblEmpMaster getTblEmpMasterByGoodsReceiptLmu() {
        return this.tblEmpMasterByGoodsReceiptLmu;
    }
    
    public void setTblEmpMasterByGoodsReceiptLmu(TblEmpMaster tblEmpMasterByGoodsReceiptLmu) {
        this.tblEmpMasterByGoodsReceiptLmu = tblEmpMasterByGoodsReceiptLmu;
    }
    public TblEmpMaster getTblEmpMasterByGoodsReceiptCreatedby() {
        return this.tblEmpMasterByGoodsReceiptCreatedby;
    }
    
    public void setTblEmpMasterByGoodsReceiptCreatedby(TblEmpMaster tblEmpMasterByGoodsReceiptCreatedby) {
        this.tblEmpMasterByGoodsReceiptCreatedby = tblEmpMasterByGoodsReceiptCreatedby;
    }
    public TblEmpMaster getTblEmpMasterByGoodsReceiptApprovedby() {
        return this.tblEmpMasterByGoodsReceiptApprovedby;
    }
    
    public void setTblEmpMasterByGoodsReceiptApprovedby(TblEmpMaster tblEmpMasterByGoodsReceiptApprovedby) {
        this.tblEmpMasterByGoodsReceiptApprovedby = tblEmpMasterByGoodsReceiptApprovedby;
    }
    public TblEmpMaster getTblEmpMasterByGoodsReceiptFinalApprovedby() {
        return this.tblEmpMasterByGoodsReceiptFinalApprovedby;
    }
    
    public void setTblEmpMasterByGoodsReceiptFinalApprovedby(TblEmpMaster tblEmpMasterByGoodsReceiptFinalApprovedby) {
        this.tblEmpMasterByGoodsReceiptFinalApprovedby = tblEmpMasterByGoodsReceiptFinalApprovedby;
    }
    public TblEmpMaster getTblEmpMasterByGoodsReceiptStoresby() {
        return this.tblEmpMasterByGoodsReceiptStoresby;
    }
    
    public void setTblEmpMasterByGoodsReceiptStoresby(TblEmpMaster tblEmpMasterByGoodsReceiptStoresby) {
        this.tblEmpMasterByGoodsReceiptStoresby = tblEmpMasterByGoodsReceiptStoresby;
    }
    public TblIndentDetails getTblIndentDetails() {
        return this.tblIndentDetails;
    }
    
    public void setTblIndentDetails(TblIndentDetails tblIndentDetails) {
        this.tblIndentDetails = tblIndentDetails;
    }
    public TblIndentMaster getTblIndentMaster() {
        return this.tblIndentMaster;
    }
    
    public void setTblIndentMaster(TblIndentMaster tblIndentMaster) {
        this.tblIndentMaster = tblIndentMaster;
    }
    public TblIndentStatus getTblIndentStatusByGoodsReceiptFinalStatus() {
        return this.tblIndentStatusByGoodsReceiptFinalStatus;
    }
    
    public void setTblIndentStatusByGoodsReceiptFinalStatus(TblIndentStatus tblIndentStatusByGoodsReceiptFinalStatus) {
        this.tblIndentStatusByGoodsReceiptFinalStatus = tblIndentStatusByGoodsReceiptFinalStatus;
    }
    public TblIndentStatus getTblIndentStatusByGoodsReceiptStoresbyStatus() {
        return this.tblIndentStatusByGoodsReceiptStoresbyStatus;
    }
    
    public void setTblIndentStatusByGoodsReceiptStoresbyStatus(TblIndentStatus tblIndentStatusByGoodsReceiptStoresbyStatus) {
        this.tblIndentStatusByGoodsReceiptStoresbyStatus = tblIndentStatusByGoodsReceiptStoresbyStatus;
    }
    public TblIndentStatus getTblIndentStatusByGoodsReceiptApprovedStatus() {
        return this.tblIndentStatusByGoodsReceiptApprovedStatus;
    }
    
    public void setTblIndentStatusByGoodsReceiptApprovedStatus(TblIndentStatus tblIndentStatusByGoodsReceiptApprovedStatus) {
        this.tblIndentStatusByGoodsReceiptApprovedStatus = tblIndentStatusByGoodsReceiptApprovedStatus;
    }
    public BigDecimal getGoodsReceiptQuantity() {
        return this.goodsReceiptQuantity;
    }
    
    public void setGoodsReceiptQuantity(BigDecimal goodsReceiptQuantity) {
        this.goodsReceiptQuantity = goodsReceiptQuantity;
    }
    public BigDecimal getGoodsReceiptIssuedQuantity() {
        return this.goodsReceiptIssuedQuantity;
    }
    
    public void setGoodsReceiptIssuedQuantity(BigDecimal goodsReceiptIssuedQuantity) {
        this.goodsReceiptIssuedQuantity = goodsReceiptIssuedQuantity;
    }
    public BigDecimal getGoodsReceiptBalanceInventory() {
        return this.goodsReceiptBalanceInventory;
    }
    
    public void setGoodsReceiptBalanceInventory(BigDecimal goodsReceiptBalanceInventory) {
        this.goodsReceiptBalanceInventory = goodsReceiptBalanceInventory;
    }
    public BigDecimal getGoodsReceiptOpeningQuantity() {
        return this.goodsReceiptOpeningQuantity;
    }
    
    public void setGoodsReceiptOpeningQuantity(BigDecimal goodsReceiptOpeningQuantity) {
        this.goodsReceiptOpeningQuantity = goodsReceiptOpeningQuantity;
    }
    public String getGoodsReceiptCreatedDate() {
        return this.goodsReceiptCreatedDate;
    }
    
    public void setGoodsReceiptCreatedDate(String goodsReceiptCreatedDate) {
        this.goodsReceiptCreatedDate = goodsReceiptCreatedDate;
    }
    public String getGoodsReceiptCreatedRemarks() {
        return this.goodsReceiptCreatedRemarks;
    }
    
    public void setGoodsReceiptCreatedRemarks(String goodsReceiptCreatedRemarks) {
        this.goodsReceiptCreatedRemarks = goodsReceiptCreatedRemarks;
    }
    public String getGoodsReceiptApprovedbyDate() {
        return this.goodsReceiptApprovedbyDate;
    }
    
    public void setGoodsReceiptApprovedbyDate(String goodsReceiptApprovedbyDate) {
        this.goodsReceiptApprovedbyDate = goodsReceiptApprovedbyDate;
    }
    public String getGoodsReceiptApprovedbyRemarks() {
        return this.goodsReceiptApprovedbyRemarks;
    }
    
    public void setGoodsReceiptApprovedbyRemarks(String goodsReceiptApprovedbyRemarks) {
        this.goodsReceiptApprovedbyRemarks = goodsReceiptApprovedbyRemarks;
    }
    public String getGoodsReceiptFinalApprovedbyDate() {
        return this.goodsReceiptFinalApprovedbyDate;
    }
    
    public void setGoodsReceiptFinalApprovedbyDate(String goodsReceiptFinalApprovedbyDate) {
        this.goodsReceiptFinalApprovedbyDate = goodsReceiptFinalApprovedbyDate;
    }
    public String getGoodsReceiptFinalApprovedbyRemarks() {
        return this.goodsReceiptFinalApprovedbyRemarks;
    }
    
    public void setGoodsReceiptFinalApprovedbyRemarks(String goodsReceiptFinalApprovedbyRemarks) {
        this.goodsReceiptFinalApprovedbyRemarks = goodsReceiptFinalApprovedbyRemarks;
    }
    public BigDecimal getGoodsReceiptRequestedQuantity() {
        return this.goodsReceiptRequestedQuantity;
    }
    
    public void setGoodsReceiptRequestedQuantity(BigDecimal goodsReceiptRequestedQuantity) {
        this.goodsReceiptRequestedQuantity = goodsReceiptRequestedQuantity;
    }
    public BigDecimal getGoodsReceiptBalanceQuantityStores() {
        return this.goodsReceiptBalanceQuantityStores;
    }
    
    public void setGoodsReceiptBalanceQuantityStores(BigDecimal goodsReceiptBalanceQuantityStores) {
        this.goodsReceiptBalanceQuantityStores = goodsReceiptBalanceQuantityStores;
    }
    public String getGoodsReceiptStoresbyDate() {
        return this.goodsReceiptStoresbyDate;
    }
    
    public void setGoodsReceiptStoresbyDate(String goodsReceiptStoresbyDate) {
        this.goodsReceiptStoresbyDate = goodsReceiptStoresbyDate;
    }
    public String getGoodsReceiptStoresbyRemarks() {
        return this.goodsReceiptStoresbyRemarks;
    }
    
    public void setGoodsReceiptStoresbyRemarks(String goodsReceiptStoresbyRemarks) {
        this.goodsReceiptStoresbyRemarks = goodsReceiptStoresbyRemarks;
    }
    public int getGoodsReceiptStatus() {
        return this.goodsReceiptStatus;
    }
    
    public void setGoodsReceiptStatus(int goodsReceiptStatus) {
        this.goodsReceiptStatus = goodsReceiptStatus;
    }
    public String getGoodsReceiptLmd() {
        return this.goodsReceiptLmd;
    }
    
    public void setGoodsReceiptLmd(String goodsReceiptLmd) {
        this.goodsReceiptLmd = goodsReceiptLmd;
    }




}


