package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblIndentMaster generated by hbm2java
 */
public class TblIndentMaster  implements java.io.Serializable {


     private Integer indentId;
     private TblCompanyMaster tblCompanyMaster;
     private TblDepartmentMaster tblDepartmentMaster;
     private TblEmpMaster tblEmpMasterByIndentEmp;
     private TblEmpMaster tblEmpMasterByIndentLmu;
     private TblEmpMaster tblEmpMasterByIndentFinalApprovedby;
     private TblEmpMaster tblEmpMasterByIndentProcurementby;
     private TblEmpMaster tblEmpMasterByIndentCreatedby;
     private TblEmpMaster tblEmpMasterByIndentApprovedby;
     private TblIndentStatus tblIndentStatusByIndentFinalStatus;
     private TblIndentStatus tblIndentStatusByIndentProcurementStatus;
     private TblIndentStatus tblIndentStatusByIndentApprovedStatus;
     private TblSectionMaster tblSectionMaster;
     private TblPlantMaster tblPlantMaster;
     private String indentNo;
     private String indentYear;
     private String indentDate;
     private String indentComments;
     private String indentDeliveryDate;
     private String indentPoNumber;
     private String indentApprovedbyDate;
     private String indentRemarks;
     private String indentFinalDate;
     private String indentFinalRemarks;
     private int indentStatus;
     private Date indentLmd;
     private Set tblIndentDetailses = new HashSet(0);
     private Set tblIndentProcurementLogses = new HashSet(0);

    public TblIndentMaster() {
    }

	
    public TblIndentMaster(TblCompanyMaster tblCompanyMaster, TblDepartmentMaster tblDepartmentMaster, TblEmpMaster tblEmpMasterByIndentEmp, TblEmpMaster tblEmpMasterByIndentLmu, TblEmpMaster tblEmpMasterByIndentCreatedby, TblSectionMaster tblSectionMaster, TblPlantMaster tblPlantMaster, String indentNo, String indentYear, String indentDate, int indentStatus, Date indentLmd) {
        this.tblCompanyMaster = tblCompanyMaster;    
        this.tblDepartmentMaster = tblDepartmentMaster;
        this.tblEmpMasterByIndentEmp = tblEmpMasterByIndentEmp;
        this.tblEmpMasterByIndentLmu = tblEmpMasterByIndentLmu;
        this.tblEmpMasterByIndentCreatedby = tblEmpMasterByIndentCreatedby;
        this.tblSectionMaster = tblSectionMaster;
        this.tblPlantMaster = tblPlantMaster;
        this.indentNo = indentNo;
        this.indentYear = indentYear;
        this.indentDate = indentDate;
        this.indentStatus = indentStatus;
        this.indentLmd = indentLmd;
    }
    public TblIndentMaster(TblCompanyMaster tblCompanyMaster, TblDepartmentMaster tblDepartmentMaster, TblEmpMaster tblEmpMasterByIndentEmp, TblEmpMaster tblEmpMasterByIndentLmu, TblEmpMaster tblEmpMasterByIndentFinalApprovedby, TblEmpMaster tblEmpMasterByIndentProcurementby, TblEmpMaster tblEmpMasterByIndentCreatedby, TblEmpMaster tblEmpMasterByIndentApprovedby, TblIndentStatus tblIndentStatusByIndentFinalStatus, TblIndentStatus tblIndentStatusByIndentProcurementStatus, TblIndentStatus tblIndentStatusByIndentApprovedStatus, TblSectionMaster tblSectionMaster, TblPlantMaster tblPlantMaster, String indentNo, String indentYear, String indentDate, String indentComments, String indentDeliveryDate, String indentPoNumber, String indentApprovedbyDate, String indentRemarks, String indentFinalDate, String indentFinalRemarks, int indentStatus, Date indentLmd, Set tblIndentDetailses, Set tblIndentProcurementLogses) {
       this.tblCompanyMaster = tblCompanyMaster; 
       this.tblDepartmentMaster = tblDepartmentMaster;
       this.tblEmpMasterByIndentEmp = tblEmpMasterByIndentEmp;
       this.tblEmpMasterByIndentLmu = tblEmpMasterByIndentLmu;
       this.tblEmpMasterByIndentFinalApprovedby = tblEmpMasterByIndentFinalApprovedby;
       this.tblEmpMasterByIndentProcurementby = tblEmpMasterByIndentProcurementby;
       this.tblEmpMasterByIndentCreatedby = tblEmpMasterByIndentCreatedby;
       this.tblEmpMasterByIndentApprovedby = tblEmpMasterByIndentApprovedby;
       this.tblIndentStatusByIndentFinalStatus = tblIndentStatusByIndentFinalStatus;
       this.tblIndentStatusByIndentProcurementStatus = tblIndentStatusByIndentProcurementStatus;
       this.tblIndentStatusByIndentApprovedStatus = tblIndentStatusByIndentApprovedStatus;
       this.tblSectionMaster = tblSectionMaster;
       this.tblPlantMaster = tblPlantMaster;
       this.indentNo = indentNo;
       this.indentYear = indentYear;
       this.indentDate = indentDate;
       this.indentComments = indentComments;
       this.indentDeliveryDate = indentDeliveryDate;
       this.indentPoNumber = indentPoNumber;
       this.indentApprovedbyDate = indentApprovedbyDate;
       this.indentRemarks = indentRemarks;
       this.indentFinalDate = indentFinalDate;
       this.indentFinalRemarks = indentFinalRemarks;
       this.indentStatus = indentStatus;
       this.indentLmd = indentLmd;
       this.tblIndentDetailses = tblIndentDetailses;
       this.tblIndentProcurementLogses = tblIndentProcurementLogses;
    }
   
    public Integer getIndentId() {
        return this.indentId;
    }
    
    public void setIndentId(Integer indentId) {
        this.indentId = indentId;
    }
    public TblCompanyMaster getTblCompanyMaster() {
        return this.tblCompanyMaster;
    }
    
    public void setTblCompanyMaster(TblCompanyMaster tblCompanyMaster) {
        this.tblCompanyMaster = tblCompanyMaster;
    }
    public TblDepartmentMaster getTblDepartmentMaster() {
        return this.tblDepartmentMaster;
    }
    
    public void setTblDepartmentMaster(TblDepartmentMaster tblDepartmentMaster) {
        this.tblDepartmentMaster = tblDepartmentMaster;
    }
    public TblEmpMaster getTblEmpMasterByIndentEmp() {
        return this.tblEmpMasterByIndentEmp;
    }
    
    public void setTblEmpMasterByIndentEmp(TblEmpMaster tblEmpMasterByIndentEmp) {
        this.tblEmpMasterByIndentEmp = tblEmpMasterByIndentEmp;
    }
    public TblEmpMaster getTblEmpMasterByIndentLmu() {
        return this.tblEmpMasterByIndentLmu;
    }
    
    public void setTblEmpMasterByIndentLmu(TblEmpMaster tblEmpMasterByIndentLmu) {
        this.tblEmpMasterByIndentLmu = tblEmpMasterByIndentLmu;
    }
    public TblEmpMaster getTblEmpMasterByIndentFinalApprovedby() {
        return this.tblEmpMasterByIndentFinalApprovedby;
    }
    
    public void setTblEmpMasterByIndentFinalApprovedby(TblEmpMaster tblEmpMasterByIndentFinalApprovedby) {
        this.tblEmpMasterByIndentFinalApprovedby = tblEmpMasterByIndentFinalApprovedby;
    }
    public TblEmpMaster getTblEmpMasterByIndentProcurementby() {
        return this.tblEmpMasterByIndentProcurementby;
    }
    
    public void setTblEmpMasterByIndentProcurementby(TblEmpMaster tblEmpMasterByIndentProcurementby) {
        this.tblEmpMasterByIndentProcurementby = tblEmpMasterByIndentProcurementby;
    }
    public TblEmpMaster getTblEmpMasterByIndentCreatedby() {
        return this.tblEmpMasterByIndentCreatedby;
    }
    
    public void setTblEmpMasterByIndentCreatedby(TblEmpMaster tblEmpMasterByIndentCreatedby) {
        this.tblEmpMasterByIndentCreatedby = tblEmpMasterByIndentCreatedby;
    }
    public TblEmpMaster getTblEmpMasterByIndentApprovedby() {
        return this.tblEmpMasterByIndentApprovedby;
    }
    
    public void setTblEmpMasterByIndentApprovedby(TblEmpMaster tblEmpMasterByIndentApprovedby) {
        this.tblEmpMasterByIndentApprovedby = tblEmpMasterByIndentApprovedby;
    }
    public TblIndentStatus getTblIndentStatusByIndentFinalStatus() {
        return this.tblIndentStatusByIndentFinalStatus;
    }
    
    public void setTblIndentStatusByIndentFinalStatus(TblIndentStatus tblIndentStatusByIndentFinalStatus) {
        this.tblIndentStatusByIndentFinalStatus = tblIndentStatusByIndentFinalStatus;
    }
    public TblIndentStatus getTblIndentStatusByIndentProcurementStatus() {
        return this.tblIndentStatusByIndentProcurementStatus;
    }
    
    public void setTblIndentStatusByIndentProcurementStatus(TblIndentStatus tblIndentStatusByIndentProcurementStatus) {
        this.tblIndentStatusByIndentProcurementStatus = tblIndentStatusByIndentProcurementStatus;
    }
    public TblIndentStatus getTblIndentStatusByIndentApprovedStatus() {
        return this.tblIndentStatusByIndentApprovedStatus;
    }
    
    public void setTblIndentStatusByIndentApprovedStatus(TblIndentStatus tblIndentStatusByIndentApprovedStatus) {
        this.tblIndentStatusByIndentApprovedStatus = tblIndentStatusByIndentApprovedStatus;
    }
    public TblSectionMaster getTblSectionMaster() {
        return this.tblSectionMaster;
    }
    
    public void setTblSectionMaster(TblSectionMaster tblSectionMaster) {
        this.tblSectionMaster = tblSectionMaster;
    }
    public TblPlantMaster getTblPlantMaster() {
        return this.tblPlantMaster;
    }
    
    public void setTblPlantMaster(TblPlantMaster tblPlantMaster) {
        this.tblPlantMaster = tblPlantMaster;
    }
    public String getIndentNo() {
        return this.indentNo;
    }
    
    public void setIndentNo(String indentNo) {
        this.indentNo = indentNo;
    }
    public String getIndentYear() {
        return this.indentYear;
    }
    
    public void setIndentYear(String indentYear) {
        this.indentYear = indentYear;
    }
    public String getIndentDate() {
        return this.indentDate;
    }
    
    public void setIndentDate(String indentDate) {
        this.indentDate = indentDate;
    }
    public String getIndentComments() {
        return this.indentComments;
    }
    
    public void setIndentComments(String indentComments) {
        this.indentComments = indentComments;
    }
    public String getIndentDeliveryDate() {
        return this.indentDeliveryDate;
    }
    
    public void setIndentDeliveryDate(String indentDeliveryDate) {
        this.indentDeliveryDate = indentDeliveryDate;
    }
    public String getIndentPoNumber() {
        return this.indentPoNumber;
    }
    
    public void setIndentPoNumber(String indentPoNumber) {
        this.indentPoNumber = indentPoNumber;
    }
    public String getIndentApprovedbyDate() {
        return this.indentApprovedbyDate;
    }
    
    public void setIndentApprovedbyDate(String indentApprovedbyDate) {
        this.indentApprovedbyDate = indentApprovedbyDate;
    }
    public String getIndentRemarks() {
        return this.indentRemarks;
    }
    
    public void setIndentRemarks(String indentRemarks) {
        this.indentRemarks = indentRemarks;
    }
    public String getIndentFinalDate() {
        return this.indentFinalDate;
    }
    
    public void setIndentFinalDate(String indentFinalDate) {
        this.indentFinalDate = indentFinalDate;
    }
    public String getIndentFinalRemarks() {
        return this.indentFinalRemarks;
    }
    
    public void setIndentFinalRemarks(String indentFinalRemarks) {
        this.indentFinalRemarks = indentFinalRemarks;
    }
    public int getIndentStatus() {
        return this.indentStatus;
    }
    
    public void setIndentStatus(int indentStatus) {
        this.indentStatus = indentStatus;
    }
    public Date getIndentLmd() {
        return this.indentLmd;
    }
    
    public void setIndentLmd(Date indentLmd) {
        this.indentLmd = indentLmd;
    }
    public Set getTblIndentDetailses() {
        return this.tblIndentDetailses;
    }
    
    public void setTblIndentDetailses(Set tblIndentDetailses) {
        this.tblIndentDetailses = tblIndentDetailses;
    }
    public Set getTblIndentProcurementLogses() {
        return this.tblIndentProcurementLogses;
    }
    
    public void setTblIndentProcurementLogses(Set tblIndentProcurementLogses) {
        this.tblIndentProcurementLogses = tblIndentProcurementLogses;
    }

   
    
    




}


