package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TblIndentDetails generated by hbm2java
 */
public class TblIndentDetails  implements java.io.Serializable {


     private Integer indentDetailsId;
     private TblEmpMaster tblEmpMaster;
     private TblIndentMaster tblIndentMaster;
     private TblMaterialMaster tblMaterialMaster;
     private TblUmoMaster tblUmoMaster;
     private BigDecimal indentDetailsQty;
     private BigDecimal indentDetailsRmQty;
     private BigDecimal indentDetailsDeptQty;
     private BigDecimal indentDetailsStockAval;
     private BigDecimal indentDetailsPricing;
     private String indentDetailsPurpose;
     private String indentDetailsVendor;
     private int indentDetailsStatus;
     private Date indentDetailsLmd;

    public TblIndentDetails() {
    }

	
    public TblIndentDetails(TblEmpMaster tblEmpMaster, TblIndentMaster tblIndentMaster, TblMaterialMaster tblMaterialMaster, TblUmoMaster tblUmoMaster, BigDecimal indentDetailsQty, BigDecimal indentDetailsStockAval, int indentDetailsStatus, Date indentDetailsLmd) {
        this.tblEmpMaster = tblEmpMaster;
        this.tblIndentMaster = tblIndentMaster;
        this.tblMaterialMaster = tblMaterialMaster;
        this.tblUmoMaster = tblUmoMaster;
        this.indentDetailsQty = indentDetailsQty;
        this.indentDetailsStockAval = indentDetailsStockAval;
        this.indentDetailsStatus = indentDetailsStatus;
        this.indentDetailsLmd = indentDetailsLmd;
    }
    public TblIndentDetails(TblEmpMaster tblEmpMaster, TblIndentMaster tblIndentMaster, TblMaterialMaster tblMaterialMaster, TblUmoMaster tblUmoMaster, BigDecimal indentDetailsQty, BigDecimal indentDetailsRmQty, BigDecimal indentDetailsDeptQty, BigDecimal indentDetailsStockAval, BigDecimal indentDetailsPricing, String indentDetailsPurpose, String indentDetailsVendor, int indentDetailsStatus, Date indentDetailsLmd) {
       this.tblEmpMaster = tblEmpMaster;
       this.tblIndentMaster = tblIndentMaster;
       this.tblMaterialMaster = tblMaterialMaster;
       this.tblUmoMaster = tblUmoMaster;
       this.indentDetailsQty = indentDetailsQty;
       this.indentDetailsRmQty = indentDetailsRmQty;
       this.indentDetailsDeptQty = indentDetailsDeptQty;
       this.indentDetailsStockAval = indentDetailsStockAval;
       this.indentDetailsPricing = indentDetailsPricing;
       this.indentDetailsPurpose = indentDetailsPurpose;
       this.indentDetailsVendor = indentDetailsVendor;
       this.indentDetailsStatus = indentDetailsStatus;
       this.indentDetailsLmd = indentDetailsLmd;
    }
   
    public Integer getIndentDetailsId() {
        return this.indentDetailsId;
    }
    
    public void setIndentDetailsId(Integer indentDetailsId) {
        this.indentDetailsId = indentDetailsId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public TblIndentMaster getTblIndentMaster() {
        return this.tblIndentMaster;
    }
    
    public void setTblIndentMaster(TblIndentMaster tblIndentMaster) {
        this.tblIndentMaster = tblIndentMaster;
    }
    public TblMaterialMaster getTblMaterialMaster() {
        return this.tblMaterialMaster;
    }
    
    public void setTblMaterialMaster(TblMaterialMaster tblMaterialMaster) {
        this.tblMaterialMaster = tblMaterialMaster;
    }
    public TblUmoMaster getTblUmoMaster() {
        return this.tblUmoMaster;
    }
    
    public void setTblUmoMaster(TblUmoMaster tblUmoMaster) {
        this.tblUmoMaster = tblUmoMaster;
    }
    public BigDecimal getIndentDetailsQty() {
        return this.indentDetailsQty;
    }
    
    public void setIndentDetailsQty(BigDecimal indentDetailsQty) {
        this.indentDetailsQty = indentDetailsQty;
    }
    public BigDecimal getIndentDetailsRmQty() {
        return this.indentDetailsRmQty;
    }
    
    public void setIndentDetailsRmQty(BigDecimal indentDetailsRmQty) {
        this.indentDetailsRmQty = indentDetailsRmQty;
    }
    public BigDecimal getIndentDetailsDeptQty() {
        return this.indentDetailsDeptQty;
    }
    
    public void setIndentDetailsDeptQty(BigDecimal indentDetailsDeptQty) {
        this.indentDetailsDeptQty = indentDetailsDeptQty;
    }
    public BigDecimal getIndentDetailsStockAval() {
        return this.indentDetailsStockAval;
    }
    
    public void setIndentDetailsStockAval(BigDecimal indentDetailsStockAval) {
        this.indentDetailsStockAval = indentDetailsStockAval;
    }
    public BigDecimal getIndentDetailsPricing() {
        return this.indentDetailsPricing;
    }
    
    public void setIndentDetailsPricing(BigDecimal indentDetailsPricing) {
        this.indentDetailsPricing = indentDetailsPricing;
    }
    public String getIndentDetailsPurpose() {
        return this.indentDetailsPurpose;
    }
    
    public void setIndentDetailsPurpose(String indentDetailsPurpose) {
        this.indentDetailsPurpose = indentDetailsPurpose;
    }
    public String getIndentDetailsVendor() {
        return this.indentDetailsVendor;
    }
    
    public void setIndentDetailsVendor(String indentDetailsVendor) {
        this.indentDetailsVendor = indentDetailsVendor;
    }
    public int getIndentDetailsStatus() {
        return this.indentDetailsStatus;
    }
    
    public void setIndentDetailsStatus(int indentDetailsStatus) {
        this.indentDetailsStatus = indentDetailsStatus;
    }
    public Date getIndentDetailsLmd() {
        return this.indentDetailsLmd;
    }
    
    public void setIndentDetailsLmd(Date indentDetailsLmd) {
        this.indentDetailsLmd = indentDetailsLmd;
    }




}


