package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


/**
 * TblIssueNote generated by hbm2java
 */
public class TblIssueNote  implements java.io.Serializable {


     private Integer issueNoteId;
     private TblEmpMaster tblEmpMasterByIssueNoteStoresby;
     private TblEmpMaster tblEmpMasterByIssueNoteLmu;
     private TblEmpMaster tblEmpMasterByIssueNoteApprovedby;
     private TblEmpMaster tblEmpMasterByIssueNoteCreatedby;
     private TblIndentStatus tblIndentStatusByIssueNoteApprovedStatus;
     private TblIndentStatus tblIndentStatusByIssueNoteStoresbyStatus;
     private TblCompanyMaster tblCompanyMaster;
     private TblDepartmentMaster tblDepartmentMaster;
     private TblSectionMaster tblSectionMaster;
     private TblPlantMaster tblPlantMaster;
     private String issueNoteYear;
     private String issueNoteNo;
     private String issueNoteCreatedDate;
     private String issueNoteCreatedRemarks;
     private String issueNoteApprovedbyDate;
     private String issueNoteApprovedbyRemarks;
     private String issueNoteStoresbyDate;
     private String issueNoteStoresbyRemarks;
     private int issueNoteStatus;
     private String issueNoteLmd;

    public TblIssueNote() {
    }

	
    public TblIssueNote(TblEmpMaster tblEmpMasterByIssueNoteLmu, TblCompanyMaster tblCompanyMaster, TblDepartmentMaster tblDepartmentMaster, TblSectionMaster tblSectionMaster, TblPlantMaster tblPlantMaster, int issueNoteStatus, String issueNoteLmd) {        this.tblEmpMasterByIssueNoteLmu = tblEmpMasterByIssueNoteLmu;
        this.tblCompanyMaster = tblCompanyMaster;
        this.tblDepartmentMaster = tblDepartmentMaster;
        this.tblSectionMaster = tblSectionMaster;
        this.tblPlantMaster =tblPlantMaster;
        this.issueNoteStatus = issueNoteStatus;
        this.issueNoteLmd = issueNoteLmd;
    }
    public TblIssueNote(TblEmpMaster tblEmpMasterByIssueNoteStoresby, TblEmpMaster tblEmpMasterByIssueNoteLmu, TblEmpMaster tblEmpMasterByIssueNoteApprovedby, TblEmpMaster tblEmpMasterByIssueNoteCreatedby, TblIndentStatus tblIndentStatusByIssueNoteApprovedStatus, TblIndentStatus tblIndentStatusByIssueNoteStoresbyStatus, TblCompanyMaster tblCompanyMaster, TblDepartmentMaster tblDepartmentMaster, TblSectionMaster tblSectionMaster, TblPlantMaster tblPlantMaster, String issueNoteYear, String issueNoteNo,  String issueNoteCreatedDate, String issueNoteCreatedRemarks, String issueNoteApprovedbyDate, String issueNoteApprovedbyRemarks, String issueNoteStoresbyDate, String issueNoteStoresbyRemarks, int issueNoteStatus, String issueNoteLmd) {
       this.tblEmpMasterByIssueNoteStoresby = tblEmpMasterByIssueNoteStoresby;
       this.tblEmpMasterByIssueNoteLmu = tblEmpMasterByIssueNoteLmu;
       this.tblEmpMasterByIssueNoteApprovedby = tblEmpMasterByIssueNoteApprovedby;
       this.tblEmpMasterByIssueNoteCreatedby = tblEmpMasterByIssueNoteCreatedby;
       this.tblIndentStatusByIssueNoteApprovedStatus = tblIndentStatusByIssueNoteApprovedStatus;
       this.tblIndentStatusByIssueNoteStoresbyStatus = tblIndentStatusByIssueNoteStoresbyStatus;
       this.tblCompanyMaster = tblCompanyMaster;
       this.tblDepartmentMaster = tblDepartmentMaster;
       this.tblSectionMaster = tblSectionMaster;
       this.tblPlantMaster =tblPlantMaster;
       this.issueNoteYear=issueNoteYear;
       this.issueNoteNo=issueNoteNo;
       this.issueNoteCreatedDate = issueNoteCreatedDate;
       this.issueNoteCreatedRemarks = issueNoteCreatedRemarks;
       this.issueNoteApprovedbyDate = issueNoteApprovedbyDate;
       this.issueNoteApprovedbyRemarks = issueNoteApprovedbyRemarks;
       this.issueNoteStoresbyDate = issueNoteStoresbyDate;
       this.issueNoteStoresbyRemarks = issueNoteStoresbyRemarks;
       this.issueNoteStatus = issueNoteStatus;
       this.issueNoteLmd = issueNoteLmd;
    }
   
    public Integer getIssueNoteId() {
        return this.issueNoteId;
    }
    
    public void setIssueNoteId(Integer issueNoteId) {
        this.issueNoteId = issueNoteId;
    }
    public TblEmpMaster getTblEmpMasterByIssueNoteStoresby() {
        return this.tblEmpMasterByIssueNoteStoresby;
    }
    
    public void setTblEmpMasterByIssueNoteStoresby(TblEmpMaster tblEmpMasterByIssueNoteStoresby) {
        this.tblEmpMasterByIssueNoteStoresby = tblEmpMasterByIssueNoteStoresby;
    }
    public TblEmpMaster getTblEmpMasterByIssueNoteLmu() {
        return this.tblEmpMasterByIssueNoteLmu;
    }
    
    public void setTblEmpMasterByIssueNoteLmu(TblEmpMaster tblEmpMasterByIssueNoteLmu) {
        this.tblEmpMasterByIssueNoteLmu = tblEmpMasterByIssueNoteLmu;
    }
    public TblEmpMaster getTblEmpMasterByIssueNoteApprovedby() {
        return this.tblEmpMasterByIssueNoteApprovedby;
    }
    
    public void setTblEmpMasterByIssueNoteApprovedby(TblEmpMaster tblEmpMasterByIssueNoteApprovedby) {
        this.tblEmpMasterByIssueNoteApprovedby = tblEmpMasterByIssueNoteApprovedby;
    }
    public TblEmpMaster getTblEmpMasterByIssueNoteCreatedby() {
        return this.tblEmpMasterByIssueNoteCreatedby;
    }
    
    public void setTblEmpMasterByIssueNoteCreatedby(TblEmpMaster tblEmpMasterByIssueNoteCreatedby) {
        this.tblEmpMasterByIssueNoteCreatedby = tblEmpMasterByIssueNoteCreatedby;
    }
    public TblIndentStatus getTblIndentStatusByIssueNoteApprovedStatus() {
        return this.tblIndentStatusByIssueNoteApprovedStatus;
    }
    
    public void setTblIndentStatusByIssueNoteApprovedStatus(TblIndentStatus tblIndentStatusByIssueNoteApprovedStatus) {
        this.tblIndentStatusByIssueNoteApprovedStatus = tblIndentStatusByIssueNoteApprovedStatus;
    }
    public TblIndentStatus getTblIndentStatusByIssueNoteStoresbyStatus() {
        return this.tblIndentStatusByIssueNoteStoresbyStatus;
    }
    
    public void setTblIndentStatusByIssueNoteStoresbyStatus(TblIndentStatus tblIndentStatusByIssueNoteStoresbyStatus) {
        this.tblIndentStatusByIssueNoteStoresbyStatus = tblIndentStatusByIssueNoteStoresbyStatus;
    }
    
    public TblCompanyMaster getTblCompanyMaster() {
        return this.tblCompanyMaster;
    }
    
    public void setTblCompanyMaster(TblCompanyMaster tblCompanyMaster) {
        this.tblCompanyMaster = tblCompanyMaster;
    }

    public TblDepartmentMaster getTblDepartmentMaster() {
        return tblDepartmentMaster;
    }

    public void setTblDepartmentMaster(TblDepartmentMaster tblDepartmentMaster) {
        this.tblDepartmentMaster = tblDepartmentMaster;
    }

    public TblSectionMaster getTblSectionMaster() {
        return tblSectionMaster;
    }

    public void setTblSectionMaster(TblSectionMaster tblSectionMaster) {
        this.tblSectionMaster = tblSectionMaster;
    }

    public TblPlantMaster getTblPlantMaster() {
        return tblPlantMaster;
    }

    public void setTblPlantMaster(TblPlantMaster tblPlantMaster) {
        this.tblPlantMaster = tblPlantMaster;
    }

    public String getIssueNoteYear() {
        return issueNoteYear;
    }

    public void setIssueNoteYear(String issueNoteYear) {
        this.issueNoteYear = issueNoteYear;
    }

    public String getIssueNoteNo() {
        return issueNoteNo;
    }

    public void setIssueNoteNo(String issueNoteNo) {
        this.issueNoteNo = issueNoteNo;
    }
    
    public String getIssueNoteCreatedDate() {
        return this.issueNoteCreatedDate;
    }
    
    public void setIssueNoteCreatedDate(String issueNoteCreatedDate) {
        this.issueNoteCreatedDate = issueNoteCreatedDate;
    }
    public String getIssueNoteCreatedRemarks() {
        return this.issueNoteCreatedRemarks;
    }
    
    public void setIssueNoteCreatedRemarks(String issueNoteCreatedRemarks) {
        this.issueNoteCreatedRemarks = issueNoteCreatedRemarks;
    }
    public String getIssueNoteApprovedbyDate() {
        return this.issueNoteApprovedbyDate;
    }
    
    public void setIssueNoteApprovedbyDate(String issueNoteApprovedbyDate) {
        this.issueNoteApprovedbyDate = issueNoteApprovedbyDate;
    }
    public String getIssueNoteApprovedbyRemarks() {
        return this.issueNoteApprovedbyRemarks;
    }
    
    public void setIssueNoteApprovedbyRemarks(String issueNoteApprovedbyRemarks) {
        this.issueNoteApprovedbyRemarks = issueNoteApprovedbyRemarks;
    }
    
    public String getIssueNoteStoresbyDate() {
        return this.issueNoteStoresbyDate;
    }
    
    public void setIssueNoteStoresbyDate(String issueNoteStoresbyDate) {
        this.issueNoteStoresbyDate = issueNoteStoresbyDate;
    }
    public String getIssueNoteStoresbyRemarks() {
        return this.issueNoteStoresbyRemarks;
    }
    
    public void setIssueNoteStoresbyRemarks(String issueNoteStoresbyRemarks) {
        this.issueNoteStoresbyRemarks = issueNoteStoresbyRemarks;
    }
    public int getIssueNoteStatus() {
        return this.issueNoteStatus;
    }
    
    public void setIssueNoteStatus(int issueNoteStatus) {
        this.issueNoteStatus = issueNoteStatus;
    }
    public String getIssueNoteLmd() {
        return this.issueNoteLmd;
    }
    
    public void setIssueNoteLmd(String issueNoteLmd) {
        this.issueNoteLmd = issueNoteLmd;
    }

}


