package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblIndentProcurementLogs generated by hbm2java
 */
public class TblIndentProcurementLogs  implements java.io.Serializable {


     private Integer indentProcurementId;
     private TblEmpMaster tblEmpMaster;
     private TblIndentMaster tblIndentMaster;
     private TblIndentStatus tblIndentStatus;
     private String indentProcurementRemarks;
     private String indentProcurementDate;
     private int indentProcurementStatus;
     private Date indentProcurementLmd;

    public TblIndentProcurementLogs() {
    }

	
    public TblIndentProcurementLogs(TblEmpMaster tblEmpMaster, TblIndentMaster tblIndentMaster, TblIndentStatus tblIndentStatus, String indentProcurementDate, int indentProcurementStatus, Date indentProcurementLmd) {
        this.tblEmpMaster = tblEmpMaster;
        this.tblIndentMaster = tblIndentMaster;
        this.tblIndentStatus = tblIndentStatus;
        this.indentProcurementDate = indentProcurementDate;
        this.indentProcurementStatus = indentProcurementStatus;
        this.indentProcurementLmd = indentProcurementLmd;
    }
    public TblIndentProcurementLogs(TblEmpMaster tblEmpMaster, TblIndentMaster tblIndentMaster, TblIndentStatus tblIndentStatus, String indentProcurementRemarks, String indentProcurementDate, int indentProcurementStatus, Date indentProcurementLmd) {
       this.tblEmpMaster = tblEmpMaster;
       this.tblIndentMaster = tblIndentMaster;
       this.tblIndentStatus = tblIndentStatus;
       this.indentProcurementRemarks = indentProcurementRemarks;
       this.indentProcurementDate = indentProcurementDate;
       this.indentProcurementStatus = indentProcurementStatus;
       this.indentProcurementLmd = indentProcurementLmd;
    }
   
    public Integer getIndentProcurementId() {
        return this.indentProcurementId;
    }
    
    public void setIndentProcurementId(Integer indentProcurementId) {
        this.indentProcurementId = indentProcurementId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public TblIndentMaster getTblIndentMaster() {
        return this.tblIndentMaster;
    }
    
    public void setTblIndentMaster(TblIndentMaster tblIndentMaster) {
        this.tblIndentMaster = tblIndentMaster;
    }
    public TblIndentStatus getTblIndentStatus() {
        return this.tblIndentStatus;
    }
    
    public void setTblIndentStatus(TblIndentStatus tblIndentStatus) {
        this.tblIndentStatus = tblIndentStatus;
    }
    public String getIndentProcurementRemarks() {
        return this.indentProcurementRemarks;
    }
    
    public void setIndentProcurementRemarks(String indentProcurementRemarks) {
        this.indentProcurementRemarks = indentProcurementRemarks;
    }
    public String getIndentProcurementDate() {
        return this.indentProcurementDate;
    }
    
    public void setIndentProcurementDate(String indentProcurementDate) {
        this.indentProcurementDate = indentProcurementDate;
    }
    public int getIndentProcurementStatus() {
        return this.indentProcurementStatus;
    }
    
    public void setIndentProcurementStatus(int indentProcurementStatus) {
        this.indentProcurementStatus = indentProcurementStatus;
    }
    public Date getIndentProcurementLmd() {
        return this.indentProcurementLmd;
    }
    
    public void setIndentProcurementLmd(Date indentProcurementLmd) {
        this.indentProcurementLmd = indentProcurementLmd;
    }




}


