package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TblIssueNoteDetails generated by hbm2java
 */
public class TblIssueNoteDetails  implements java.io.Serializable {


     private Integer issueNoteDetailsId;
     private TblEmpMaster tblEmpMaster;
     private TblIssueNote tblIssueNote;
     private TblMaterialMaster tblMaterialMaster;
     private BigDecimal issueNoteDetailsQuantity;
     private BigDecimal issueNoteDetailsIssuedQuantity;
     private BigDecimal issueNoteDetailsBalanceInventory;
     private BigDecimal issueNoteDetailsOpeningQuantity;
     private BigDecimal issueNoteDetailsRequestedQuantity;
     private BigDecimal issueNoteDetailsQuantityStores;
     private int issueNoteDetailsStatus;
     private String issueNoteDetailsLmd;

    public TblIssueNoteDetails() {
    }

	
    public TblIssueNoteDetails(TblEmpMaster tblEmpMaster, TblIssueNote tblIssueNote, TblMaterialMaster tblMaterialMaster, int issueNoteDetailsStatus, String issueNoteDetailsLmd) {
        this.tblEmpMaster = tblEmpMaster;
        this.tblIssueNote = tblIssueNote;
        this.tblMaterialMaster = tblMaterialMaster;
        this.issueNoteDetailsStatus = issueNoteDetailsStatus;
        this.issueNoteDetailsLmd = issueNoteDetailsLmd;
    }
    public TblIssueNoteDetails(TblEmpMaster tblEmpMaster, TblIssueNote tblIssueNote, TblMaterialMaster tblMaterialMaster, BigDecimal issueNoteDetailsQuantity, BigDecimal issueNoteDetailsIssuedQuantity, BigDecimal issueNoteDetailsBalanceInventory, BigDecimal issueNoteDetailsOpeningQuantity, BigDecimal issueNoteDetailsRequestedQuantity, BigDecimal issueNoteDetailsQuantityStores, int issueNoteDetailsStatus, String issueNoteDetailsLmd) {
       this.tblEmpMaster = tblEmpMaster;
       this.tblIssueNote = tblIssueNote;
       this.tblMaterialMaster = tblMaterialMaster;
       this.issueNoteDetailsQuantity = issueNoteDetailsQuantity;
       this.issueNoteDetailsIssuedQuantity = issueNoteDetailsIssuedQuantity;
       this.issueNoteDetailsBalanceInventory = issueNoteDetailsBalanceInventory;
       this.issueNoteDetailsOpeningQuantity = issueNoteDetailsOpeningQuantity;
       this.issueNoteDetailsRequestedQuantity = issueNoteDetailsRequestedQuantity;
       this.issueNoteDetailsQuantityStores = issueNoteDetailsQuantityStores;
       this.issueNoteDetailsStatus = issueNoteDetailsStatus;
       this.issueNoteDetailsLmd = issueNoteDetailsLmd;
    }
   
    public Integer getIssueNoteDetailsId() {
        return this.issueNoteDetailsId;
    }
    
    public void setIssueNoteDetailsId(Integer issueNoteDetailsId) {
        this.issueNoteDetailsId = issueNoteDetailsId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public TblIssueNote getTblIssueNote() {
        return this.tblIssueNote;
    }
    
    public void setTblIssueNote(TblIssueNote tblIssueNote) {
        this.tblIssueNote = tblIssueNote;
    }
    public TblMaterialMaster getTblMaterialMaster() {
        return this.tblMaterialMaster;
    }
    
    public void setTblMaterialMaster(TblMaterialMaster tblMaterialMaster) {
        this.tblMaterialMaster = tblMaterialMaster;
    }
    public BigDecimal getIssueNoteDetailsQuantity() {
        return this.issueNoteDetailsQuantity;
    }
    
    public void setIssueNoteDetailsQuantity(BigDecimal issueNoteDetailsQuantity) {
        this.issueNoteDetailsQuantity = issueNoteDetailsQuantity;
    }
    public BigDecimal getIssueNoteDetailsIssuedQuantity() {
        return this.issueNoteDetailsIssuedQuantity;
    }
    
    public void setIssueNoteDetailsIssuedQuantity(BigDecimal issueNoteDetailsIssuedQuantity) {
        this.issueNoteDetailsIssuedQuantity = issueNoteDetailsIssuedQuantity;
    }
    public BigDecimal getIssueNoteDetailsBalanceInventory() {
        return this.issueNoteDetailsBalanceInventory;
    }
    
    public void setIssueNoteDetailsBalanceInventory(BigDecimal issueNoteDetailsBalanceInventory) {
        this.issueNoteDetailsBalanceInventory = issueNoteDetailsBalanceInventory;
    }
    public BigDecimal getIssueNoteDetailsOpeningQuantity() {
        return this.issueNoteDetailsOpeningQuantity;
    }
    
    public void setIssueNoteDetailsOpeningQuantity(BigDecimal issueNoteDetailsOpeningQuantity) {
        this.issueNoteDetailsOpeningQuantity = issueNoteDetailsOpeningQuantity;
    }
    public BigDecimal getIssueNoteDetailsRequestedQuantity() {
        return this.issueNoteDetailsRequestedQuantity;
    }
    
    public void setIssueNoteDetailsRequestedQuantity(BigDecimal issueNoteDetailsRequestedQuantity) {
        this.issueNoteDetailsRequestedQuantity = issueNoteDetailsRequestedQuantity;
    }
    public BigDecimal getIssueNoteDetailsQuantityStores() {
        return this.issueNoteDetailsQuantityStores;
    }
    
    public void setIssueNoteDetailsQuantityStores(BigDecimal issueNoteDetailsQuantityStores) {
        this.issueNoteDetailsQuantityStores = issueNoteDetailsQuantityStores;
    }
    public int getIssueNoteDetailsStatus() {
        return this.issueNoteDetailsStatus;
    }
    
    public void setIssueNoteDetailsStatus(int issueNoteDetailsStatus) {
        this.issueNoteDetailsStatus = issueNoteDetailsStatus;
    }
    public String getIssueNoteDetailsLmd() {
        return this.issueNoteDetailsLmd;
    }
    
    public void setIssueNoteDetailsLmd(String issueNoteDetailsLmd) {
        this.issueNoteDetailsLmd = issueNoteDetailsLmd;
    }




}


