package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblIndentStatus generated by hbm2java
 */
public class TblIndentStatus  implements java.io.Serializable {


     private Integer indentStatusId;
     private TblEmpMaster tblEmpMaster;
     private String indentStatusName;
     private int indentStatus;
     private Date indentLmd;

    public TblIndentStatus() {
    }

    public TblIndentStatus(TblEmpMaster tblEmpMaster, String indentStatusName, int indentStatus, Date indentLmd) {
       this.tblEmpMaster = tblEmpMaster;
       this.indentStatusName = indentStatusName;
       this.indentStatus = indentStatus;
       this.indentLmd = indentLmd;
    }
   
    public Integer getIndentStatusId() {
        return this.indentStatusId;
    }
    
    public void setIndentStatusId(Integer indentStatusId) {
        this.indentStatusId = indentStatusId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getIndentStatusName() {
        return this.indentStatusName;
    }
    
    public void setIndentStatusName(String indentStatusName) {
        this.indentStatusName = indentStatusName;
    }
    public int getIndentStatus() {
        return this.indentStatus;
    }
    
    public void setIndentStatus(int indentStatus) {
        this.indentStatus = indentStatus;
    }
    public Date getIndentLmd() {
        return this.indentLmd;
    }
    
    public void setIndentLmd(Date indentLmd) {
        this.indentLmd = indentLmd;
    }




}


