package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblLocationMaster generated by hbm2java
 */
public class TblLocationMaster  implements java.io.Serializable {


     private Integer locId;
     private TblEmpMaster tblEmpMaster;
     private String locCode;
     private String locName;
     private int locStatus;
     private Date locLmd;
     private Set tblMapCompanyLocations = new HashSet(0);
     private Set tblEmpMasters = new HashSet(0);

    public TblLocationMaster() {
    }

	
    public TblLocationMaster(String locName, int locStatus, Date locLmd) {
        this.locName = locName;
        this.locStatus = locStatus;
        this.locLmd = locLmd;
    }
    public TblLocationMaster(TblEmpMaster tblEmpMaster, String locCode, String locName, int locStatus, Date locLmd, Set tblMapCompanyLocations, Set tblEmpMasters) {
       this.tblEmpMaster = tblEmpMaster;
       this.locCode = locCode;
       this.locName = locName;
       this.locStatus = locStatus;
       this.locLmd = locLmd;
       this.tblMapCompanyLocations = tblMapCompanyLocations;
       this.tblEmpMasters = tblEmpMasters;
    }
   
    public Integer getLocId() {
        return this.locId;
    }
    
    public void setLocId(Integer locId) {
        this.locId = locId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }
    public String getLocName() {
        return this.locName;
    }
    
    public void setLocName(String locName) {
        this.locName = locName;
    }
    public int getLocStatus() {
        return this.locStatus;
    }
    
    public void setLocStatus(int locStatus) {
        this.locStatus = locStatus;
    }
    public Date getLocLmd() {
        return this.locLmd;
    }
    
    public void setLocLmd(Date locLmd) {
        this.locLmd = locLmd;
    }
    public Set getTblMapCompanyLocations() {
        return this.tblMapCompanyLocations;
    }
    
    public void setTblMapCompanyLocations(Set tblMapCompanyLocations) {
        this.tblMapCompanyLocations = tblMapCompanyLocations;
    }
    public Set getTblEmpMasters() {
        return this.tblEmpMasters;
    }
    
    public void setTblEmpMasters(Set tblEmpMasters) {
        this.tblEmpMasters = tblEmpMasters;
    }




}


