package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1



/**
 * TblLdapConfig generated by hbm2java
 */
public class TblLdapConfig  implements java.io.Serializable {


     private Integer configId;
     private String configDomine;
     private String configUrl;
     private String configUser;
     private String configPwd;
     private String configPrinc;
     private String configLmd;
     private int configLmu;

    public TblLdapConfig() {
    }

    public TblLdapConfig(String configDomine, String configUrl, String configUser, String configPwd, String configPrinc, String configLmd, int configLmu) {
       this.configDomine = configDomine;
       this.configUrl = configUrl;
       this.configUser = configUser;
       this.configPwd = configPwd;
       this.configPrinc = configPrinc;
       this.configLmd = configLmd;
       this.configLmu = configLmu;
    }
   
    public Integer getConfigId() {
        return this.configId;
    }
    
    public void setConfigId(Integer configId) {
        this.configId = configId;
    }
    public String getConfigDomine() {
        return this.configDomine;
    }
    
    public void setConfigDomine(String configDomine) {
        this.configDomine = configDomine;
    }
    public String getConfigUrl() {
        return this.configUrl;
    }
    
    public void setConfigUrl(String configUrl) {
        this.configUrl = configUrl;
    }
    public String getConfigUser() {
        return this.configUser;
    }
    
    public void setConfigUser(String configUser) {
        this.configUser = configUser;
    }
    public String getConfigPwd() {
        return this.configPwd;
    }
    
    public void setConfigPwd(String configPwd) {
        this.configPwd = configPwd;
    }
    public String getConfigPrinc() {
        return this.configPrinc;
    }
    
    public void setConfigPrinc(String configPrinc) {
        this.configPrinc = configPrinc;
    }
    public String getConfigLmd() {
        return this.configLmd;
    }
    
    public void setConfigLmd(String configLmd) {
        this.configLmd = configLmd;
    }
    public int getConfigLmu() {
        return this.configLmu;
    }
    
    public void setConfigLmu(int configLmu) {
        this.configLmu = configLmu;
    }




}


