package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblMapEmpReporting generated by hbm2java
 */
public class TblMapEmpReporting  implements java.io.Serializable {


     private Integer reportId;
     private TblEmpMaster tblEmpMasterByReportLmu;
     private TblEmpMaster tblEmpMasterByReportSub;
     private TblEmpMaster tblEmpMasterByReportSup;
     private Date reportStart;
     private Date reportEnd;
     private int reportStatus;
     private Date reportLmd;

    public TblMapEmpReporting() {
    }

    public TblMapEmpReporting(TblEmpMaster tblEmpMasterByReportLmu, TblEmpMaster tblEmpMasterByReportSub, TblEmpMaster tblEmpMasterByReportSup, Date reportStart, Date reportEnd, int reportStatus, Date reportLmd) {
       this.tblEmpMasterByReportLmu = tblEmpMasterByReportLmu;
       this.tblEmpMasterByReportSub = tblEmpMasterByReportSub;
       this.tblEmpMasterByReportSup = tblEmpMasterByReportSup;
       this.reportStart = reportStart;
       this.reportEnd = reportEnd;
       this.reportStatus = reportStatus;
       this.reportLmd = reportLmd;
    }
   
    public Integer getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }
    public TblEmpMaster getTblEmpMasterByReportLmu() {
        return this.tblEmpMasterByReportLmu;
    }
    
    public void setTblEmpMasterByReportLmu(TblEmpMaster tblEmpMasterByReportLmu) {
        this.tblEmpMasterByReportLmu = tblEmpMasterByReportLmu;
    }
    public TblEmpMaster getTblEmpMasterByReportSub() {
        return this.tblEmpMasterByReportSub;
    }
    
    public void setTblEmpMasterByReportSub(TblEmpMaster tblEmpMasterByReportSub) {
        this.tblEmpMasterByReportSub = tblEmpMasterByReportSub;
    }
    public TblEmpMaster getTblEmpMasterByReportSup() {
        return this.tblEmpMasterByReportSup;
    }
    
    public void setTblEmpMasterByReportSup(TblEmpMaster tblEmpMasterByReportSup) {
        this.tblEmpMasterByReportSup = tblEmpMasterByReportSup;
    }
    public Date getReportStart() {
        return this.reportStart;
    }
    
    public void setReportStart(Date reportStart) {
        this.reportStart = reportStart;
    }
    public Date getReportEnd() {
        return this.reportEnd;
    }
    
    public void setReportEnd(Date reportEnd) {
        this.reportEnd = reportEnd;
    }
    public int getReportStatus() {
        return this.reportStatus;
    }
    
    public void setReportStatus(int reportStatus) {
        this.reportStatus = reportStatus;
    }
    public Date getReportLmd() {
        return this.reportLmd;
    }
    
    public void setReportLmd(Date reportLmd) {
        this.reportLmd = reportLmd;
    }




}


