package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblMapCompanyDepartment generated by hbm2java
 */
public class TblMapCompanyDepartment  implements java.io.Serializable {


     private Integer mapId;
     private TblCompanyMaster tblCompanyMaster;
     private TblDepartmentMaster tblDepartmentMaster;
     private TblEmpMaster tblEmpMaster;
     private int mapStatus;
     private Date mapLmd;

    public TblMapCompanyDepartment() {
    }

    public TblMapCompanyDepartment(TblCompanyMaster tblCompanyMaster, TblDepartmentMaster tblDepartmentMaster, TblEmpMaster tblEmpMaster, int mapStatus, Date mapLmd) {
       this.tblCompanyMaster = tblCompanyMaster;
       this.tblDepartmentMaster = tblDepartmentMaster;
       this.tblEmpMaster = tblEmpMaster;
       this.mapStatus = mapStatus;
       this.mapLmd = mapLmd;
    }
   
    public Integer getMapId() {
        return this.mapId;
    }
    
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }
    public TblCompanyMaster getTblCompanyMaster() {
        return this.tblCompanyMaster;
    }
    
    public void setTblCompanyMaster(TblCompanyMaster tblCompanyMaster) {
        this.tblCompanyMaster = tblCompanyMaster;
    }
    public TblDepartmentMaster getTblDepartmentMaster() {
        return this.tblDepartmentMaster;
    }
    
    public void setTblDepartmentMaster(TblDepartmentMaster tblDepartmentMaster) {
        this.tblDepartmentMaster = tblDepartmentMaster;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public int getMapStatus() {
        return this.mapStatus;
    }
    
    public void setMapStatus(int mapStatus) {
        this.mapStatus = mapStatus;
    }
    public Date getMapLmd() {
        return this.mapLmd;
    }
    
    public void setMapLmd(Date mapLmd) {
        this.mapLmd = mapLmd;
    }




}


