package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TblMapCompanyPlantMaterial generated by hbm2java
 */
public class TblMapCompanyPlantMaterial  implements java.io.Serializable {


     private Integer mapId;
     private TblCompanyMaster tblCompanyMaster;
     private TblEmpMaster tblEmpMaster;
     private TblMaterialMaster tblMaterialMaster;
     private TblPlantMaster tblPlantMaster;
     private BigDecimal mapQuantityStores;
     private int mapStatus;
     private Date mapLmd;

    public TblMapCompanyPlantMaterial() {
    }

    public TblMapCompanyPlantMaterial(TblCompanyMaster tblCompanyMaster, TblEmpMaster tblEmpMaster, TblMaterialMaster tblMaterialMaster, TblPlantMaster tblPlantMaster, BigDecimal mapQuantityStores, int mapStatus, Date mapLmd) {
       this.tblCompanyMaster = tblCompanyMaster;
       this.tblEmpMaster = tblEmpMaster;
       this.tblMaterialMaster = tblMaterialMaster;
       this.tblPlantMaster = tblPlantMaster;
       this.mapQuantityStores=mapQuantityStores;
       this.mapStatus = mapStatus;
       this.mapLmd = mapLmd;
    }
   
    public Integer getMapId() {
        return this.mapId;
    }
    
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }
    
    public TblCompanyMaster getTblCompanyMaster() {
        return this.tblCompanyMaster;
    }
    
    public void setTblCompanyMaster(TblCompanyMaster tblCompanyMaster) {
        this.tblCompanyMaster = tblCompanyMaster;
    }
    
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public TblMaterialMaster getTblMaterialMaster() {
        return this.tblMaterialMaster;
    }
    
    public void setTblMaterialMaster(TblMaterialMaster tblMaterialMaster) {
        this.tblMaterialMaster = tblMaterialMaster;
    }
    
    public TblPlantMaster getTblPlantMaster() {
        return this.tblPlantMaster;
    }
    
    public void setTblPlantMaster(TblPlantMaster tblPlantMaster) {
        this.tblPlantMaster = tblPlantMaster;
    }

    public BigDecimal getMapQuantityStores() {
        return mapQuantityStores;
    }

    public void setMapQuantityStores(BigDecimal mapQuantityStores) {
        this.mapQuantityStores = mapQuantityStores;
    }
    
    public int getMapStatus() {
        return this.mapStatus;
    }
    
    public void setMapStatus(int mapStatus) {
        this.mapStatus = mapStatus;
    }
    
    public Date getMapLmd() {
        return this.mapLmd;
    }
    
    public void setMapLmd(Date mapLmd) {
        this.mapLmd = mapLmd;
    }




}


