package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblMapCompanyLocation generated by hbm2java
 */
public class TblMapCompanyLocation  implements java.io.Serializable {


     private Integer mapId;
     private TblCompanyMaster tblCompanyMaster;
     private TblEmpMaster tblEmpMaster;
     private TblLocationMaster tblLocationMaster;
     private int mapStatus;
     private Date mapLmd;

    public TblMapCompanyLocation() {
    }

    public TblMapCompanyLocation(TblCompanyMaster tblCompanyMaster, TblEmpMaster tblEmpMaster, TblLocationMaster tblLocationMaster, int mapStatus, Date mapLmd) {
       this.tblCompanyMaster = tblCompanyMaster;
       this.tblEmpMaster = tblEmpMaster;
       this.tblLocationMaster = tblLocationMaster;
       this.mapStatus = mapStatus;
       this.mapLmd = mapLmd;
    }
   
    public Integer getMapId() {
        return this.mapId;
    }
    
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }
    public TblCompanyMaster getTblCompanyMaster() {
        return this.tblCompanyMaster;
    }
    
    public void setTblCompanyMaster(TblCompanyMaster tblCompanyMaster) {
        this.tblCompanyMaster = tblCompanyMaster;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public TblLocationMaster getTblLocationMaster() {
        return this.tblLocationMaster;
    }
    
    public void setTblLocationMaster(TblLocationMaster tblLocationMaster) {
        this.tblLocationMaster = tblLocationMaster;
    }
    public int getMapStatus() {
        return this.mapStatus;
    }
    
    public void setMapStatus(int mapStatus) {
        this.mapStatus = mapStatus;
    }
    public Date getMapLmd() {
        return this.mapLmd;
    }
    
    public void setMapLmd(Date mapLmd) {
        this.mapLmd = mapLmd;
    }




}


