package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblMapEmpRoles generated by hbm2java
 */
public class TblMapEmpRoles  implements java.io.Serializable {


     private Integer empRolesId;
     private TblEmpMaster tblEmpMasterByEmpNumber;
     private TblEmpMaster tblEmpMasterByEmpRolesLmu;
     private TblRolesMaster tblRolesMaster;
     private int empRolesStatus;
     private Date empRolesLmd;

    public TblMapEmpRoles() {
    }

    public TblMapEmpRoles(TblEmpMaster tblEmpMasterByEmpNumber, TblEmpMaster tblEmpMasterByEmpRolesLmu, TblRolesMaster tblRolesMaster, int empRolesStatus, Date empRolesLmd) {
       this.tblEmpMasterByEmpNumber = tblEmpMasterByEmpNumber;
       this.tblEmpMasterByEmpRolesLmu = tblEmpMasterByEmpRolesLmu;
       this.tblRolesMaster = tblRolesMaster;
       this.empRolesStatus = empRolesStatus;
       this.empRolesLmd = empRolesLmd;
    }
   
    public Integer getEmpRolesId() {
        return this.empRolesId;
    }
    
    public void setEmpRolesId(Integer empRolesId) {
        this.empRolesId = empRolesId;
    }
    public TblEmpMaster getTblEmpMasterByEmpNumber() {
        return this.tblEmpMasterByEmpNumber;
    }
    
    public void setTblEmpMasterByEmpNumber(TblEmpMaster tblEmpMasterByEmpNumber) {
        this.tblEmpMasterByEmpNumber = tblEmpMasterByEmpNumber;
    }
    public TblEmpMaster getTblEmpMasterByEmpRolesLmu() {
        return this.tblEmpMasterByEmpRolesLmu;
    }
    
    public void setTblEmpMasterByEmpRolesLmu(TblEmpMaster tblEmpMasterByEmpRolesLmu) {
        this.tblEmpMasterByEmpRolesLmu = tblEmpMasterByEmpRolesLmu;
    }
    public TblRolesMaster getTblRolesMaster() {
        return this.tblRolesMaster;
    }
    
    public void setTblRolesMaster(TblRolesMaster tblRolesMaster) {
        this.tblRolesMaster = tblRolesMaster;
    }
    public int getEmpRolesStatus() {
        return this.empRolesStatus;
    }
    
    public void setEmpRolesStatus(int empRolesStatus) {
        this.empRolesStatus = empRolesStatus;
    }
    public Date getEmpRolesLmd() {
        return this.empRolesLmd;
    }
    
    public void setEmpRolesLmd(Date empRolesLmd) {
        this.empRolesLmd = empRolesLmd;
    }




}


