package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblMapCompanyEmp generated by hbm2java
 */
public class TblMapCompanyEmp  implements java.io.Serializable {


     private Integer mapId;
     private TblCompanyMaster tblCompanyMaster;
     private TblEmpMaster tblEmpMasterByMapEmp;
     private TblEmpMaster tblEmpMasterByMapLmu;
     private int mapStatus;
     private Date mapLmd;

    public TblMapCompanyEmp() {
    }

    public TblMapCompanyEmp(TblCompanyMaster tblCompanyMaster, TblEmpMaster tblEmpMasterByMapEmp, TblEmpMaster tblEmpMasterByMapLmu, int mapStatus, Date mapLmd) {
       this.tblCompanyMaster = tblCompanyMaster;
       this.tblEmpMasterByMapEmp = tblEmpMasterByMapEmp;
       this.tblEmpMasterByMapLmu = tblEmpMasterByMapLmu;
       this.mapStatus = mapStatus;
       this.mapLmd = mapLmd;
    }
   
    public Integer getMapId() {
        return this.mapId;
    }
    
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }
    public TblCompanyMaster getTblCompanyMaster() {
        return this.tblCompanyMaster;
    }
    
    public void setTblCompanyMaster(TblCompanyMaster tblCompanyMaster) {
        this.tblCompanyMaster = tblCompanyMaster;
    }
    public TblEmpMaster getTblEmpMasterByMapEmp() {
        return this.tblEmpMasterByMapEmp;
    }
    
    public void setTblEmpMasterByMapEmp(TblEmpMaster tblEmpMasterByMapEmp) {
        this.tblEmpMasterByMapEmp = tblEmpMasterByMapEmp;
    }
    public TblEmpMaster getTblEmpMasterByMapLmu() {
        return this.tblEmpMasterByMapLmu;
    }
    
    public void setTblEmpMasterByMapLmu(TblEmpMaster tblEmpMasterByMapLmu) {
        this.tblEmpMasterByMapLmu = tblEmpMasterByMapLmu;
    }
    public int getMapStatus() {
        return this.mapStatus;
    }
    
    public void setMapStatus(int mapStatus) {
        this.mapStatus = mapStatus;
    }
    public Date getMapLmd() {
        return this.mapLmd;
    }
    
    public void setMapLmd(Date mapLmd) {
        this.mapLmd = mapLmd;
    }




}


