package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblMaterialMaster generated by hbm2java
 */
public class TblMaterialMaster  implements java.io.Serializable {


     private Integer materialId;
     private TblEmpMaster tblEmpMaster;
     private String materialCode;
     private String materialName;
     private String materialDesc;
     //private BigDecimal materialQuantityStores;
     private int materialStatus;
     private Date materialLmd;
     private Set tblMapCompanyLocationMaterials = new HashSet(0);

    public TblMaterialMaster() {
    }

	
    public TblMaterialMaster(TblEmpMaster tblEmpMaster, String materialName, String materialDesc, int materialStatus, Date materialLmd) {
        this.tblEmpMaster = tblEmpMaster;
        this.materialName = materialName;
        this.materialDesc = materialDesc;
       // this.materialQuantityStores=materialQuantityStores;
        this.materialStatus = materialStatus;
        this.materialLmd = materialLmd;
    }
    public TblMaterialMaster(TblEmpMaster tblEmpMaster, String materialCode, String materialName, String materialDesc, int materialStatus, Date materialLmd, Set tblMapCompanyLocationMaterials) {
       this.tblEmpMaster = tblEmpMaster;
       this.materialCode = materialCode;
       this.materialName = materialName;
       this.materialDesc = materialDesc;
       //this.materialQuantityStores=materialQuantityStores;
       this.materialStatus = materialStatus;
       this.materialLmd = materialLmd;
       this.tblMapCompanyLocationMaterials = tblMapCompanyLocationMaterials;
    }
   
    public Integer getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getMaterialCode() {
        return this.materialCode;
    }
    
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode;
    }
    public String getMaterialName() {
        return this.materialName;
    }
    
    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }
    public String getMaterialDesc() {
        return this.materialDesc;
    }

    /*public BigDecimal getMaterialQuantityStores() {
        return materialQuantityStores;
    }

    public void setMaterialQuantityStores(BigDecimal materialQuantityStores) {
        this.materialQuantityStores = materialQuantityStores;
    }*/
    
    public void setMaterialDesc(String materialDesc) {
        this.materialDesc = materialDesc;
    }
    public int getMaterialStatus() {
        return this.materialStatus;
    }
    
    public void setMaterialStatus(int materialStatus) {
        this.materialStatus = materialStatus;
    }
    public Date getMaterialLmd() {
        return this.materialLmd;
    }
    
    public void setMaterialLmd(Date materialLmd) {
        this.materialLmd = materialLmd;
    }
    public Set getTblMapCompanyLocationMaterials() {
        return this.tblMapCompanyLocationMaterials;
    }
    
    public void setTblMapCompanyLocationMaterials(Set tblMapCompanyLocationMaterials) {
        this.tblMapCompanyLocationMaterials = tblMapCompanyLocationMaterials;
    }




}


