package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblPlantMaster generated by hbm2java
 */
public class TblPlantMaster  implements java.io.Serializable {


     private Integer plantId;
     private TblEmpMaster tblEmpMaster;
     private TblPzCompanyMaster tblPzCompanyMaster;    
     private String plantCode;
     private String plantName;
     private int plantStatus;
     private Date plantLmd;

    public TblPlantMaster() {
    }

    public TblPlantMaster(TblEmpMaster tblEmpMaster, TblPzCompanyMaster tblPzCompanyMaster, String plantCode, String plantName, int plantStatus, Date plantLmd) {
        this.tblEmpMaster = tblEmpMaster;
        this.tblPzCompanyMaster = tblPzCompanyMaster;
        this.plantCode = plantCode;
        this.plantName = plantName;
        this.plantStatus = plantStatus;
        this.plantLmd = plantLmd;
    }

    public TblPzCompanyMaster getTblPzCompanyMaster() {
        return tblPzCompanyMaster;
    }

    public void setTblPzCompanyMaster(TblPzCompanyMaster tblPzCompanyMaster) {
        this.tblPzCompanyMaster = tblPzCompanyMaster;
    }

    
    
   
    public Integer getPlantId() {
        return this.plantId;
    }
    
    public void setPlantId(Integer plantId) {
        this.plantId = plantId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getPlantCode() {
        return this.plantCode;
    }
    
    public void setPlantCode(String plantCode) {
        this.plantCode = plantCode;
    }
    public String getPlantName() {
        return this.plantName;
    }
    
    public void setPlantName(String plantName) {
        this.plantName = plantName;
    }
    public int getPlantStatus() {
        return this.plantStatus;
    }
    
    public void setPlantStatus(int plantStatus) {
        this.plantStatus = plantStatus;
    }
    public Date getPlantLmd() {
        return this.plantLmd;
    }
    
    public void setPlantLmd(Date plantLmd) {
        this.plantLmd = plantLmd;
    }




}


