package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblRolesMaster generated by hbm2java
 */
public class TblRolesMaster  implements java.io.Serializable {


     private Integer roleId;
     private TblEmpMaster tblEmpMaster;
     private String roleCode;
     private String roleName;
     private String roleView;
     private String roleAdd;
     private String roleEdit;
     private String roleDelete;
     private int roleStatus;
     private Date roleLmd;
     private Set tblMapEmpRoleses = new HashSet(0);

    public TblRolesMaster() {
    }

	
    public TblRolesMaster(TblEmpMaster tblEmpMaster, String roleName, int roleStatus, Date roleLmd) {
        this.tblEmpMaster = tblEmpMaster;
        this.roleName = roleName;
        this.roleStatus = roleStatus;
        this.roleLmd = roleLmd;
    }
    public TblRolesMaster(TblEmpMaster tblEmpMaster, String roleCode, String roleName, String roleView, String roleAdd, String roleEdit, String roleDelete, int roleStatus, Date roleLmd, Set tblMapEmpRoleses) {
       this.tblEmpMaster = tblEmpMaster;
       this.roleCode = roleCode;
       this.roleName = roleName;
       this.roleView = roleView;
       this.roleAdd = roleAdd;
       this.roleEdit = roleEdit;
       this.roleDelete = roleDelete;
       this.roleStatus = roleStatus;
       this.roleLmd = roleLmd;
       this.tblMapEmpRoleses = tblMapEmpRoleses;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getRoleCode() {
        return this.roleCode;
    }
    
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleView() {
        return this.roleView;
    }
    
    public void setRoleView(String roleView) {
        this.roleView = roleView;
    }
    public String getRoleAdd() {
        return this.roleAdd;
    }
    
    public void setRoleAdd(String roleAdd) {
        this.roleAdd = roleAdd;
    }
    public String getRoleEdit() {
        return this.roleEdit;
    }
    
    public void setRoleEdit(String roleEdit) {
        this.roleEdit = roleEdit;
    }
    public String getRoleDelete() {
        return this.roleDelete;
    }
    
    public void setRoleDelete(String roleDelete) {
        this.roleDelete = roleDelete;
    }
    public int getRoleStatus() {
        return this.roleStatus;
    }
    
    public void setRoleStatus(int roleStatus) {
        this.roleStatus = roleStatus;
    }
    public Date getRoleLmd() {
        return this.roleLmd;
    }
    
    public void setRoleLmd(Date roleLmd) {
        this.roleLmd = roleLmd;
    }
    public Set getTblMapEmpRoleses() {
        return this.tblMapEmpRoleses;
    }
    
    public void setTblMapEmpRoleses(Set tblMapEmpRoleses) {
        this.tblMapEmpRoleses = tblMapEmpRoleses;
    }




}


