package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblSectionMaster generated by hbm2java
 */
public class TblSectionMaster  implements java.io.Serializable {


     private Integer secId;
     private TblEmpMaster tblEmpMaster;
     private String secCode;
     private String secName;
     private int secStatus;
     private Date secLmd;
     private Set tblIndentMasters = new HashSet(0);

    public TblSectionMaster() {
    }

	
    public TblSectionMaster(TblEmpMaster tblEmpMaster, String secName, int secStatus, Date secLmd) {
        this.tblEmpMaster = tblEmpMaster;
        this.secName = secName;
        this.secStatus = secStatus;
        this.secLmd = secLmd;
    }
    public TblSectionMaster(TblEmpMaster tblEmpMaster, String secCode, String secName, int secStatus, Date secLmd, Set tblIndentMasters) {
       this.tblEmpMaster = tblEmpMaster;
       this.secCode = secCode;
       this.secName = secName;
       this.secStatus = secStatus;
       this.secLmd = secLmd;
       this.tblIndentMasters = tblIndentMasters;
    }
   
    public Integer getSecId() {
        return this.secId;
    }
    
    public void setSecId(Integer secId) {
        this.secId = secId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getSecCode() {
        return this.secCode;
    }
    
    public void setSecCode(String secCode) {
        this.secCode = secCode;
    }
    public String getSecName() {
        return this.secName;
    }
    
    public void setSecName(String secName) {
        this.secName = secName;
    }
    public int getSecStatus() {
        return this.secStatus;
    }
    
    public void setSecStatus(int secStatus) {
        this.secStatus = secStatus;
    }
    public Date getSecLmd() {
        return this.secLmd;
    }
    
    public void setSecLmd(Date secLmd) {
        this.secLmd = secLmd;
    }
    public Set getTblIndentMasters() {
        return this.tblIndentMasters;
    }
    
    public void setTblIndentMasters(Set tblIndentMasters) {
        this.tblIndentMasters = tblIndentMasters;
    }




}


