package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblUmoMaster generated by hbm2java
 */
public class TblUmoMaster  implements java.io.Serializable {


     private Integer umoId;
     private TblEmpMaster tblEmpMaster;
     private String umoCode;
     private String umoName;
     private int umoStatus;
     private Date umoLmd;

    public TblUmoMaster() {
    }

    public TblUmoMaster(TblEmpMaster tblEmpMaster, String umoCode, String umoName, int umoStatus, Date umoLmd) {
       this.tblEmpMaster = tblEmpMaster;
       this.umoCode = umoCode;
       this.umoName = umoName;
       this.umoStatus = umoStatus;
       this.umoLmd = umoLmd;
    }
   
    public Integer getUmoId() {
        return this.umoId;
    }
    
    public void setUmoId(Integer umoId) {
        this.umoId = umoId;
    }
    public TblEmpMaster getTblEmpMaster() {
        return this.tblEmpMaster;
    }
    
    public void setTblEmpMaster(TblEmpMaster tblEmpMaster) {
        this.tblEmpMaster = tblEmpMaster;
    }
    public String getUmoCode() {
        return this.umoCode;
    }
    
    public void setUmoCode(String umoCode) {
        this.umoCode = umoCode;
    }
    public String getUmoName() {
        return this.umoName;
    }
    
    public void setUmoName(String umoName) {
        this.umoName = umoName;
    }
    public int getUmoStatus() {
        return this.umoStatus;
    }
    
    public void setUmoStatus(int umoStatus) {
        this.umoStatus = umoStatus;
    }
    public Date getUmoLmd() {
        return this.umoLmd;
    }
    
    public void setUmoLmd(Date umoLmd) {
        this.umoLmd = umoLmd;
    }




}


