package pojo;
// Generated Mar 2, 2020 1:00:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblUserMaster generated by hbm2java
 */
public class TblUserMaster  implements java.io.Serializable {


     private Integer userId;
     private TblEmpMaster tblEmpMasterByEmpNumber;
     private TblEmpMaster tblEmpMasterByUserLmu;
     private String userName;
     private String userPassword;
     private String userLoginIp;
     private int userStatus;
     private Date userLmd;

    public TblUserMaster() {
    }

	
    public TblUserMaster(TblEmpMaster tblEmpMasterByEmpNumber, TblEmpMaster tblEmpMasterByUserLmu, String userName, String userPassword, int userStatus, Date userLmd) {
        this.tblEmpMasterByEmpNumber = tblEmpMasterByEmpNumber;
        this.tblEmpMasterByUserLmu = tblEmpMasterByUserLmu;
        this.userName = userName;
        this.userPassword = userPassword;
        this.userStatus = userStatus;
        this.userLmd = userLmd;
    }
    public TblUserMaster(TblEmpMaster tblEmpMasterByEmpNumber, TblEmpMaster tblEmpMasterByUserLmu, String userName, String userPassword, String userLoginIp, int userStatus, Date userLmd) {
       this.tblEmpMasterByEmpNumber = tblEmpMasterByEmpNumber;
       this.tblEmpMasterByUserLmu = tblEmpMasterByUserLmu;
       this.userName = userName;
       this.userPassword = userPassword;
       this.userLoginIp = userLoginIp;
       this.userStatus = userStatus;
       this.userLmd = userLmd;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public TblEmpMaster getTblEmpMasterByEmpNumber() {
        return this.tblEmpMasterByEmpNumber;
    }
    
    public void setTblEmpMasterByEmpNumber(TblEmpMaster tblEmpMasterByEmpNumber) {
        this.tblEmpMasterByEmpNumber = tblEmpMasterByEmpNumber;
    }
    public TblEmpMaster getTblEmpMasterByUserLmu() {
        return this.tblEmpMasterByUserLmu;
    }
    
    public void setTblEmpMasterByUserLmu(TblEmpMaster tblEmpMasterByUserLmu) {
        this.tblEmpMasterByUserLmu = tblEmpMasterByUserLmu;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserLoginIp() {
        return this.userLoginIp;
    }
    
    public void setUserLoginIp(String userLoginIp) {
        this.userLoginIp = userLoginIp;
    }
    public int getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(int userStatus) {
        this.userStatus = userStatus;
    }
    public Date getUserLmd() {
        return this.userLmd;
    }
    
    public void setUserLmd(Date userLmd) {
        this.userLmd = userLmd;
    }




}


