-- V32__create_missing_tables.sql
-- Creates tables currently missing from seeds_indent_replica_1 but mapped in JPA entities

-- 1. Create tbl_audit_log
CREATE TABLE IF NOT EXISTS tbl_audit_log (
    audit_id INT AUTO_INCREMENT PRIMARY KEY,
    audit_action VARCHAR(100) NOT NULL,
    audit_entity_type VARCHAR(100),
    audit_entity_id VARCHAR(100),
    audit_user_id INT,
    audit_username VARCHAR(100),
    audit_ip_address VARCHAR(45),
    audit_timestamp DATETIME(6) NOT NULL,
    audit_details TEXT,
    audit_status VARCHAR(50)
);

-- 2. Create tbl_goods_receipt
CREATE TABLE IF NOT EXISTS tbl_goods_receipt (
    goods_receipt_id INT AUTO_INCREMENT PRIMARY KEY,
    goods_receipt_no VARCHAR(100) NOT NULL UNIQUE,
    goods_receipt_date DATETIME(6) NOT NULL,
    indent_id INT NOT NULL,
    indent_details_id INT NOT NULL,
    goods_receipt_quantity DECIMAL(20,2) NOT NULL,
    goods_receipt_issued_quantity DECIMAL(20,2),
    goods_receipt_balance_inventory DECIMAL(20,2),
    goods_receipt_opening_quantity DECIMAL(20,2),
    goods_receipt_rate DECIMAL(20,2),
    goods_receipt_amount DECIMAL(20,2),
    goods_receipt_vendor VARCHAR(200),
    goods_receipt_comments TEXT,
    goods_receipt_createdby INT NOT NULL,
    goods_receipt_created_date DATETIME(6),
    goods_receipt_created_remarks TEXT,
    goods_receipt_rm_approvedby INT,
    goods_receipt_rm_approvedby_date DATETIME(6),
    goods_receipt_rm_approvedby_remarks TEXT,
    goods_receipt_rm_status INT,
    goods_receipt_approvedby INT,
    goods_receipt_approvedby_date DATETIME(6),
    goods_receipt_approvedby_remarks TEXT,
    goods_receipt_final_approvedby INT,
    goods_receipt_final_approvedby_date DATETIME(6),
    goods_receipt_final_approvedby_remarks TEXT,
    goods_receipt_requested_quantity DECIMAL(20,2),
    goods_receipt_balance_quantity_stores DECIMAL(20,2),
    goods_receipt_storesby INT,
    goods_receipt_storesby_date DATETIME(6),
    goods_receipt_storesby_remarks TEXT,
    goods_receipt_status INT NOT NULL,
    goods_receipt_approved_status INT,
    goods_receipt_final_status INT,
    goods_receipt_storesby_status INT,
    goods_receipt_supervisor_bypass TINYINT(1),
    goods_receipt_lmd DATETIME(6) NOT NULL,
    goods_receipt_lmu INT NOT NULL
);

-- 3. Create tbl_purchase_orders
CREATE TABLE IF NOT EXISTS tbl_purchase_orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    po_number VARCHAR(50) NOT NULL UNIQUE,
    po_date DATE NOT NULL,
    indent_id INT NOT NULL,
    vendor_id INT NOT NULL,
    department_id INT NOT NULL,
    po_status INT NOT NULL,
    total_amount DECIMAL(15,2) NOT NULL,
    tax_amount DECIMAL(15,2),
    discount_amount DECIMAL(15,2),
    net_amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(10),
    payment_terms VARCHAR(100),
    delivery_address TEXT,
    delivery_date DATE,
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    terms_conditions TEXT,
    notes TEXT,
    priority VARCHAR(20),
    approved_by INT,
    approved_date DATETIME(6),
    sent_to_vendor_by INT,
    sent_to_vendor_date DATETIME(6),
    cancelled_by INT,
    cancelled_date DATETIME(6),
    cancellation_reason TEXT,
    closed_by INT,
    closed_date DATETIME(6),
    created_by INT NOT NULL,
    created_date DATETIME(6) NOT NULL,
    last_modified_by INT,
    last_modified_date DATETIME(6)
);

-- 4. Create tbl_purchase_order_details
CREATE TABLE IF NOT EXISTS tbl_purchase_order_details (
    id INT AUTO_INCREMENT PRIMARY KEY,
    purchase_order_id INT NOT NULL,
    line_number INT NOT NULL,
    indent_detail_id INT NOT NULL,
    material_id INT NOT NULL,
    material_code VARCHAR(50),
    material_name VARCHAR(200) NOT NULL,
    material_description TEXT,
    quantity DECIMAL(15,3) NOT NULL,
    unit_of_measure VARCHAR(20),
    unit_price DECIMAL(15,2) NOT NULL,
    tax_rate DECIMAL(5,2),
    tax_amount DECIMAL(15,2),
    discount_rate DECIMAL(5,2),
    discount_amount DECIMAL(15,2),
    line_total DECIMAL(15,2) NOT NULL,
    received_quantity DECIMAL(15,3),
    pending_quantity DECIMAL(15,3),
    rejected_quantity DECIMAL(15,3),
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    delivery_status INT NOT NULL,
    notes TEXT,
    created_date DATETIME(6) NOT NULL,
    last_modified_date DATETIME(6),
    CONSTRAINT fk_po_details_po_id FOREIGN KEY (purchase_order_id) REFERENCES tbl_purchase_orders(id) ON DELETE CASCADE
);
